//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMUserSetup
    {
        public int TenentID { get; set; }
        public int userid { get; set; }
        public int MyID { get; set; }
        public int startupCompRefID { get; set; }
        public int StartupContactRefID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
