//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRUP_MST
    {
        public int TENANT_ID { get; set; }
        public int LocationID { get; set; }
        public long CRUP_ID { get; set; }
        public Nullable<int> MySerial { get; set; }
        public Nullable<int> MENU_ID { get; set; }
        public string PHYSICALLOCID { get; set; }
        public string ActivityNote { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
    }
}
