//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIVILEGE_MST
    {
        public int TenentID { get; set; }
        public int PRIVILEGE_ID { get; set; }
        public string PRIVILEGE_NAME { get; set; }
        public string PRIVILEGE_DESC { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public long CRUP_ID { get; set; }
        public int MODULE_ID { get; set; }
        public string PRIVILEGE_NAME1 { get; set; }
        public string PRIVILEGE_NAME2 { get; set; }
    }
}
