//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIVILAGE_MENUDemon
    {
        public int PRIVILEGE_MENU_ID { get; set; }
        public int TenentID { get; set; }
        public int PRIVILEGE_ID { get; set; }
        public int PRIVILAGEFOR { get; set; }
        public int LOCATION_ID { get; set; }
        public int MENU_ID { get; set; }
        public string IS_VISIBLE { get; set; }
        public string IS_ENABLE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public int MySerial { get; set; }
        public string ALL_FLAG { get; set; }
        public string ADD_FLAG { get; set; }
        public string MODIFY_FLAG { get; set; }
        public string DELETE_FLAG { get; set; }
        public string VIEW_FLAG { get; set; }
        public string LABEL_FLAG { get; set; }
        public Nullable<int> MASTER_ID { get; set; }
        public string MENU_LOCATION { get; set; }
        public Nullable<System.DateTime> ACTIVETILLDATE { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SP1 { get; set; }
        public string SP2 { get; set; }
        public string SP3 { get; set; }
        public string SP4 { get; set; }
        public string SP5 { get; set; }
        public string SP1Name { get; set; }
        public string SP2Name { get; set; }
        public string SP3Name { get; set; }
        public string SP4Name { get; set; }
        public string SP5Name { get; set; }
        public string ActiveMenu { get; set; }
        public string ActiveModule { get; set; }
        public string Action { get; set; }
    }
}
