//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> CId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<bool> IsComplaintUserRole { get; set; }
        public Nullable<int> TenentID { get; set; }
    }
}
