//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AirWayBill_Temp
    {
        public decimal TempId { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<long> AirwayBillNo { get; set; }
        public Nullable<System.DateTime> AWBDate { get; set; }
        public string AWBType { get; set; }
        public string DriverName { get; set; }
        public string ShipperName { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAdd1 { get; set; }
        public string ConsigneeAdd2 { get; set; }
        public string ConsigneeAdd3 { get; set; }
        public string ConsigneeCountry { get; set; }
        public string ConsigneeState { get; set; }
        public string ConsigneeCityId { get; set; }
        public string ConsigneeTelephone { get; set; }
        public string ConsigneePCS { get; set; }
        public Nullable<double> ConsigneeWeight { get; set; }
        public Nullable<double> ConsigneeNetAmount { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
