//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Awb_ConsolidationGrp
    {
        public int ID { get; set; }
        public int TenentID { get; set; }
        public int ConsolidationMstId { get; set; }
        public int AirwaybillNo { get; set; }
        public Nullable<int> MySerial { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<int> SenderDelAdrsID { get; set; }
        public Nullable<int> SenderContactMyId { get; set; }
        public Nullable<int> PackageRawID { get; set; }
        public string MyInvoicePath { get; set; }
        public string CustomDocPath { get; set; }
        public string DMSID { get; set; }
        public string InvNoRef { get; set; }
        public string Carrier { get; set; }
        public string OtherInformation { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> DriverAssiged { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
