//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashierProcess
    {
        public int Id { get; set; }
        public int TenentID { get; set; }
        public int CashierID { get; set; }
        public int AwbID { get; set; }
        public int ConsolidationId { get; set; }
        public int DriverID { get; set; }
        public int SenderID { get; set; }
        public string ReceiverID { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<decimal> AgreedAmount { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<int> DriverPaymentStatus { get; set; }
        public int PaymentStatus { get; set; }
        public string PaymentStatusDescription { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
