//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TarriefLocalRates
    {
        public int TenentID { get; set; }
        public int COUNTRYID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string AreaName { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<int> ByCompany { get; set; }
        public string AssignedRoute { get; set; }
        public string SHORTCODE { get; set; }
        public string ZONE { get; set; }
        public string SWITCH1 { get; set; }
        public string SWITCH2 { get; set; }
        public string ACTIVE1 { get; set; }
        public string ACTIVE2 { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
