//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AWBShipItems
    {
        public int Id { get; set; }
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public int PackageInvoice { get; set; }
        public string AirwayBillNo { get; set; }
        public int PackageType { get; set; }
        public int PackageRawID { get; set; }
        public int PackageSeqID { get; set; }
        public string DescriptionDisplay { get; set; }
        public string PackageDetails { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> CarrierUsed { get; set; }
        public Nullable<int> FreightForwType { get; set; }
        public string itemid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> myheight { get; set; }
        public Nullable<int> mywidth { get; set; }
        public Nullable<int> mypackagelength { get; set; }
        public Nullable<int> countryoforigin { get; set; }
        public Nullable<int> ContentType { get; set; }
        public string NetWeightUnit { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string GrossWeightUnit { get; set; }
        public Nullable<decimal> CalculatedWeight { get; set; }
        public Nullable<decimal> ChargeableWeight { get; set; }
        public Nullable<decimal> ChargesAmountForCalculation { get; set; }
        public Nullable<decimal> ChargeableWeightRatesApplied { get; set; }
        public string Currency { get; set; }
        public string QuantityUnit { get; set; }
        public Nullable<long> InvNoRef { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string HSCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}
