//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Financial
    {
        public int Id { get; set; }
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public long AirwayBillNo { get; set; }
        public int ExpenseType { get; set; }
        public int MySerial { get; set; }
        public Nullable<decimal> AgreedAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
        public string Reason { get; set; }
        public int PaymentStatus { get; set; }
        public string PaymentStatusDescription { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<int> Cashier { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> TotalPayment { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public Nullable<int> ClosingBalance { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
