//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Delivery
    {
        public int DeliveryLogId { get; set; }
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public string InvoiceNo { get; set; }
        public long AirwayBillNo { get; set; }
        public int TripNumber { get; set; }
        public string OTPNumber { get; set; }
        public string DeliveryZone { get; set; }
        public Nullable<int> DriverAssigned { get; set; }
        public Nullable<int> DriverAssignedByUser { get; set; }
        public Nullable<System.DateTime> DriverAssignedDateTime { get; set; }
        public Nullable<int> DeliveryType { get; set; }
        public Nullable<int> Receiver { get; set; }
        public Nullable<int> ReceiverDelAdrsID { get; set; }
        public string ReceiverReference { get; set; }
        public Nullable<System.DateTime> ExpDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActDeliveryDate { get; set; }
        public string DeliveryStatus { get; set; }
        public string DeliveryByUser { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public Nullable<int> ActionTaken { get; set; }
        public string ActionDescription { get; set; }
        public string DMSID { get; set; }
        public byte[] DeliveryProof { get; set; }
        public byte[] DeliveryProofSign { get; set; }
        public string Switch1 { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string syncStatus { get; set; }
    }
}
