//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAirWayMain2Packing
    {
        public int A2PKey { get; set; }
        public int AirwayBillKey { get; set; }
        public int PackingKey { get; set; }
        public int Qty { get; set; }
        public decimal Weight { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> DL { get; set; }
        public Nullable<decimal> DW { get; set; }
        public Nullable<decimal> DH { get; set; }
    }
}
