//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriverAreaBlock
    {
        public int TenentID { get; set; }
        public int locationid { get; set; }
        public int COUNTRYID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public int contactId { get; set; }
        public string Block { get; set; }
        public Nullable<int> Priority { get; set; }
        public string GoogleName { get; set; }
        public string Latitute { get; set; }
        public string Longitute { get; set; }
        public Nullable<int> crupid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string syncStatus { get; set; }
    }
}
