//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuMaster
    {
        public int MenuId { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> PMenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int CompanyId { get; set; }
    }
}
