//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRefModule
    {
        public int ID { get; set; }
        public int SequenceNumber { get; set; }
        public int ModuleID { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public string ExportCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Sort { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
