//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMaster
    {
        public int UserMasterKey { get; set; }
        public string UserCode { get; set; }
        public string UserFullName { get; set; }
        public string UserImage { get; set; }
        public byte[] UserImageByte { get; set; }
        public Nullable<int> PositionKey { get; set; }
        public string AllowToAccessLogin { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> UserActive { get; set; }
        public Nullable<int> UserRoleKey { get; set; }
        public Nullable<int> RouteKey { get; set; }
        public Nullable<int> LocationKey { get; set; }
        public Nullable<int> VehicleKey { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
