//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeFunction
    {
        public int RoleID { get; set; }
        public int NodeID { get; set; }
        public string NodeImageUrl { get; set; }
        public string NodeNavUrl { get; set; }
        public byte IsParent { get; set; }
        public int ParentID { get; set; }
        public string ReadAllow { get; set; }
        public string WriteAllow { get; set; }
        public string PrintAllow { get; set; }
        public string DeleteAllow { get; set; }
        public string Other1Allow { get; set; }
        public string Other2Allow { get; set; }
        public string Other3Allow { get; set; }
        public string Other4Allow { get; set; }
        public string Other5Allow { get; set; }
        public string PagePath { get; set; }
        public string PageTitle { get; set; }
        public string PageTitle1 { get; set; }
        public string PageTitle2 { get; set; }
        public string DashBoardImage { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> IsGraph { get; set; }
        public Nullable<byte> MenuType { get; set; }
        public Nullable<bool> IsVisibleInMenu { get; set; }
    }
}
