//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Product_Add
    {
        public int TenentID { get; set; }
        public int UserID { get; set; }
        public long MyID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public Nullable<decimal> ProductPricesh { get; set; }
        public string ProductDiscrioption { get; set; }
        public string ProductImag { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Appover { get; set; }
        public Nullable<System.DateTime> Careatdate { get; set; }
        public Nullable<decimal> SupplierPercent { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
