//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DTL
    {
        public int TenentID { get; set; }
        public int USER_DETAIL_ID { get; set; }
        public long CRUP_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string TITLE { get; set; }
        public string HOUSE_NO { get; set; }
        public string STREET { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> COUNTRY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PH_NO { get; set; }
        public string FAX_NO { get; set; }
        public string FROM_REG_DT { get; set; }
        public string VILLAGE_TOWN_CITY { get; set; }
        public string TEHSIL { get; set; }
        public string PINCODE_NO { get; set; }
        public string POST_OFFICE { get; set; }
        public string PAN_NO { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<decimal> MOBILE_NUM { get; set; }
        public string SEC_QUES { get; set; }
        public string SEC_ANS { get; set; }
    }
}
