//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCountryStateCity
    {
        public int TenentID { get; set; }
        public int COUNTRYID { get; set; }
        public string COUNAME1 { get; set; }
        public int StateID { get; set; }
        public string StateEnglish { get; set; }
        public string StateArabic { get; set; }
        public int CityID { get; set; }
        public string CityEnglish { get; set; }
        public string CityArabic { get; set; }
    }
}
