//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmSenderReceiverNew
    {
        public int TenentID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public int Id { get; set; }
        public string COMPNAME1 { get; set; }
        public string Nationality { get; set; }
        public string EMAIL { get; set; }
        public string ReferenceNumber { get; set; }
        public string PaciNumber { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateNumber { get; set; }
        public string CustomerTableAddress { get; set; }
        public string ZIPCODE { get; set; }
        public string AddressKey { get; set; }
        public string CustomerAddressName { get; set; }
        public string FlatNo { get; set; }
        public string FloorNo { get; set; }
        public string BlockNo { get; set; }
        public string Cityname { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostCode { get; set; }
    }
}
