//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAWStatusCatWise
    {
        public int TenentID { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public string Status { get; set; }
        public string AWStatus { get; set; }
        public string Sorting { get; set; }
        public string Category { get; set; }
        public string DepartmentID { get; set; }
        public string Department { get; set; }
        public string ACTIVE { get; set; }
    }
}
