//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_VoucherDetail
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int VoucherDetailID { get; set; }
        public int Voucher_ID { get; set; }
        public int Account_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public string Particular { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> ClearedBy { get; set; }
        public Nullable<System.DateTime> ClearedDate { get; set; }
        public Nullable<System.DateTime> ClearedDateTime { get; set; }
        public string PaymentType { get; set; }
    }
}
