//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHead
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int HeadID { get; set; }
        public int Family_ID { get; set; }
        public int HeadCode { get; set; }
        public string HeadName { get; set; }
        public string ArabicHeadName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> crupid { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
    }
}
