//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACMManageBanner
    {
        public long TenentID { get; set; }
        public int ACMID { get; set; }
        public int BannerID { get; set; }
        public Nullable<int> MyId { get; set; }
        public Nullable<int> SortBy { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string ACMURL { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
