//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentReceipe
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int AppointmentID { get; set; }
        public int JobID { get; set; }
        public string IOSwitch { get; set; }
        public int ItemCode { get; set; }
        public int UOM { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> msrp { get; set; }
        public Nullable<int> recNo { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string product_name { get; set; }
        public string RecipeType { get; set; }
        public string EmpOperator { get; set; }
        public Nullable<decimal> QtyIntoCostprice { get; set; }
        public string PItemCode { get; set; }
        public string PrecNo { get; set; }
    }
}
