//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankExpense
    {
        public int TenentID { get; set; }
        public int ExpID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Attachment { get; set; }
        public string RefNo { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Amount { get; set; }
        public Nullable<bool> Returnable { get; set; }
        public string Notes { get; set; }
    }
}
