//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public long TenentID { get; set; }
        public int BannerID { get; set; }
        public Nullable<int> BannerType { get; set; }
        public string BannerName { get; set; }
        public string BannerText1 { get; set; }
        public string BannerText2 { get; set; }
        public string BannerText3 { get; set; }
        public string BannerImage { get; set; }
        public Nullable<bool> isMultiBanner { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IntervalMinutes { get; set; }
        public Nullable<int> RepeatCountDay { get; set; }
        public Nullable<long> RepeatCountLogin { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string ACMURL { get; set; }
        public Nullable<int> SortBy { get; set; }
        public Nullable<int> ACMID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
