//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogForumComment
    {
        public int ID { get; set; }
        public Nullable<int> ForumID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DisplayName { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
