//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_MasterCust
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CampaignID { get; set; }
        public Nullable<int> MySerialNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> QtyConsumed { get; set; }
        public Nullable<int> AmtConsumed { get; set; }
        public string Invoice { get; set; }
        public Nullable<int> POSCounterID { get; set; }
        public Nullable<int> SalesmanID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SyncID { get; set; }
    }
}
