//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeBook
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int ChequeBookID { get; set; }
        public Nullable<int> Account_ID { get; set; }
        public Nullable<int> FromChequeNo { get; set; }
        public Nullable<int> ToChequeNo { get; set; }
        public Nullable<int> TotalCheques { get; set; }
        public Nullable<int> UsedCheques { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
