//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class COA
    {
        public int TenentID { get; set; }
        public int locationID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> Family_ID { get; set; }
        public int Head_ID { get; set; }
        public Nullable<int> SubHead_ID { get; set; }
        public Nullable<long> AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string ArabicAccountName { get; set; }
        public string OtherAccountName { get; set; }
        public int AccountType_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> crupid { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<int> SubSubHead_ID { get; set; }
    }
}
