//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint_Service
    {
        public int ServiceID { get; set; }
        public int TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
