//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMMainActivity
    {
        public int TenentID { get; set; }
        public int COMPID { get; set; }
        public int MasterCODE { get; set; }
        public int LinkMasterCODE { get; set; }
        public int LocationID { get; set; }
        public int MyID { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> USERCODE { get; set; }
        public string ACTIVITYE { get; set; }
        public string ACTIVITYA { get; set; }
        public string ACTIVITYA2 { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> AMIGLOBAL { get; set; }
        public Nullable<bool> MYPERSONNEL { get; set; }
        public Nullable<int> INTERVALDAYS { get; set; }
        public Nullable<bool> REPEATFOREVER { get; set; }
        public Nullable<System.DateTime> REPEATTILL { get; set; }
        public string REMINDERNOTE { get; set; }
        public Nullable<long> ESTCOST { get; set; }
        public Nullable<int> GROUPCODE { get; set; }
        public string USERCODEENTERED { get; set; }
        public Nullable<System.DateTime> UPDTTIME { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string Version { get; set; }
        public Nullable<int> Type { get; set; }
        public string MyStatus { get; set; }
        public Nullable<int> MainID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string DisplayFDName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Ratting { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> JobDone { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string UseReciepeName { get; set; }
        public Nullable<int> UseReciepeID { get; set; }
        public Nullable<int> TickDepartmentID { get; set; }
        public Nullable<int> TickComplainType { get; set; }
        public Nullable<int> TickPhysicalLocation { get; set; }
        public Nullable<int> TickCatID { get; set; }
        public Nullable<int> TickSubCatID { get; set; }
        public string PUseReciepeID { get; set; }
        public string Patient_Name { get; set; }
        public string MRN { get; set; }
        public Nullable<bool> StaffInvoice { get; set; }
        public Nullable<bool> IRDone { get; set; }
        public Nullable<int> ReportedBy { get; set; }
        public string ComplaintNumber { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> IncidentReport { get; set; }
        public Nullable<int> FoloEmp { get; set; }
        public string subject { get; set; }
    }
}
