//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayClose_Kitchen
    {
        public int TenentID { get; set; }
        public int locationID { get; set; }
        public int Product { get; set; }
        public int UOM { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> StoreOPBalance { get; set; }
        public Nullable<decimal> StoreClosingBalance { get; set; }
        public Nullable<decimal> StoreIN { get; set; }
        public Nullable<decimal> StoreOUT { get; set; }
        public Nullable<decimal> StoreTodayTot { get; set; }
        public Nullable<decimal> KitcOPBalance { get; set; }
        public Nullable<decimal> KitcClosingBalance { get; set; }
        public Nullable<bool> Holiday { get; set; }
    }
}
