//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eco_CRMActivitiesTikit
    {
        public int TenentID { get; set; }
        public int COMPID { get; set; }
        public Nullable<int> ActivityCompID { get; set; }
        public string ACTIVITYCODE { get; set; }
        public string ACTIVITYTYPE { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public int MyLineNo { get; set; }
        public string USERCODE { get; set; }
        public string ReferenceNo { get; set; }
        public string EarlierRefNo { get; set; }
        public string NextUser { get; set; }
        public string NextRefNo { get; set; }
        public string AMIGLOBAL { get; set; }
        public string MYPERSONNEL { get; set; }
        public string ActivityPerform { get; set; }
        public string REMINDERNOTE { get; set; }
        public int ESTCOST { get; set; }
        public string GROUPCODE { get; set; }
        public string USERCODEENTERED { get; set; }
        public Nullable<System.DateTime> UPDTTIME { get; set; }
        public string USERNAME { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public string RouteID { get; set; }
        public string Version { get; set; }
        public Nullable<int> Type { get; set; }
        public string MyStatus { get; set; }
        public string GroupBy { get; set; }
        public Nullable<int> DocID { get; set; }
        public string Active { get; set; }
        public int FromColumn { get; set; }
        public int ToColumn { get; set; }
        public string ActiveCRM { get; set; }
    }
}
