//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eco_ERP_SUPPLIER_MST
    {
        public int SUP_ID { get; set; }
        public long TenentID { get; set; }
        public int LOCATIONID { get; set; }
        public Nullable<int> SALUTATION_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_NAMEO { get; set; }
        public string DESCRIPTION { get; set; }
        public string IS_COMPANY { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string RATING { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string IMG_URL { get; set; }
        public string JOB_POSITION { get; set; }
        public string ADDRESS_ID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
