//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_COMPANY_SETUP
    {
        public Nullable<long> TenentID { get; set; }
        public long CRUP_ID { get; set; }
        public long ADDRESS_ID { get; set; }
        public int COMPANY_ID { get; set; }
        public string COMPNAME { get; set; }
        public string COMPNAMEO { get; set; }
        public string COMPNAMECH { get; set; }
        public string TAGS { get; set; }
        public string REMARKS { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public Nullable<int> BUS_ID { get; set; }
        public Nullable<int> MYCATSUB_ID { get; set; }
        public string PHYSICALLOC_ID { get; set; }
        public string ITMANAGER { get; set; }
        public string ISMINISTRY { get; set; }
        public string ISSMB { get; set; }
        public string ISCORPORATE { get; set; }
        public string INHAWALLY { get; set; }
        public string SALER { get; set; }
        public string BUYER { get; set; }
        public string SUPPLIER { get; set; }
        public string SALEDEPROD { get; set; }
        public string EMAISUB { get; set; }
        public Nullable<System.DateTime> EMAILSUBDATE { get; set; }
        public string PRODUCTDEALIN { get; set; }
        public string CUSERID { get; set; }
        public string CPASSWRD { get; set; }
        public string IMG_URL { get; set; }
    
        public virtual ERP_COMPANY_SETUP ERP_COMPANY_SETUP1 { get; set; }
        public virtual ERP_COMPANY_SETUP ERP_COMPANY_SETUP2 { get; set; }
    }
}
