//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_QUESTION_BANK
    {
        public long QUESTION_ID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string QUESTION { get; set; }
        public string QUESTION_TYPE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public Nullable<System.DateTime> REPLICATION_DT { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    
        public virtual ERP_QUESTION_BANK ERP_QUESTION_BANK1 { get; set; }
        public virtual ERP_QUESTION_BANK ERP_QUESTION_BANK2 { get; set; }
    }
}
