//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAActPredGroup
    {
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public string ActPredGroupId { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string GroupUnder { get; set; }
        public string GLSL { get; set; }
        public Nullable<int> InternalGroupId { get; set; }
        public Nullable<int> GroupType { get; set; }
        public Nullable<int> GroupSubType { get; set; }
        public string GroupNatureType { get; set; }
        public string LeftRight { get; set; }
        public string DefaultCC { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Active { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string CUSERID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    }
}
