//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAAccountGroup
    {
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public string ActGroupId { get; set; }
        public string GLSL { get; set; }
        public int InternalGroupId { get; set; }
        public string DefaultCC { get; set; }
        public string GroupUnder { get; set; }
        public int GroupType { get; set; }
        public int GroupSubType { get; set; }
        public string GroupNatureType { get; set; }
        public string GroupDesc1 { get; set; }
        public string GroupDesc2 { get; set; }
        public string GroupDesc3 { get; set; }
        public int DisplayOrder { get; set; }
        public int EffectGrossProfit { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedById { get; set; }
        public string Active { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string CUSERID { get; set; }
    }
}
