//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACashBankMaster
    {
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public int AcountId { get; set; }
        public string PreDefinedAccount { get; set; }
        public Nullable<int> ActGroupId { get; set; }
        public string SortingOrder { get; set; }
        public string AccountName1 { get; set; }
        public string AccountName2 { get; set; }
        public string AccountName3 { get; set; }
        public Nullable<int> ActType { get; set; }
        public Nullable<int> AnalysisType { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherMiti { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public string CurrentBalance { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Rate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> FYid { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ChequeMiti { get; set; }
    }
}
