//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialPeriod
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int FPeriodID { get; set; }
        public string YearCode { get; set; }
        public string DescripitonEng { get; set; }
        public string DescripitonArabic { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> crupid { get; set; }
    }
}
