//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Rec_FilterDT
    {
        public long SortNo { get; set; }
        public long SubSortNo { get; set; }
        public int MyID { get; set; }
        public string SearchWord { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> FilterRefID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> DeleteBy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<bool> isFixed { get; set; }
    
        public virtual HRMS_Rec_FilterHD HRMS_Rec_FilterHD { get; set; }
        public virtual HRMS_Rec_InputTableHD HRMS_Rec_InputTableHD { get; set; }
    }
}
