//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Rec_InputTaleDT
    {
        public long SortNo { get; set; }
        public long SubSortNo { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> FilterRefID { get; set; }
        public Nullable<bool> IsMulti { get; set; }
        public Nullable<bool> IsSingle { get; set; }
        public string MainStartPoint { get; set; }
        public Nullable<long> NextSortNo { get; set; }
        public Nullable<long> NextSubSortNo { get; set; }
        public Nullable<bool> NextLineEnd { get; set; }
        public Nullable<bool> CommaEnd { get; set; }
        public string DoubleSpacesEnd { get; set; }
        public string TextEnd { get; set; }
        public Nullable<int> StartLine { get; set; }
        public Nullable<int> EndLine { get; set; }
        public Nullable<bool> Status { get; set; }
        public string DistinationTableNAme { get; set; }
        public string DistinationTableColumn { get; set; }
        public Nullable<long> NumberOfSubSortAllowed { get; set; }
        public string SubStartPoint { get; set; }
        public Nullable<long> SubEndPointSortNo { get; set; }
        public string FunctionName { get; set; }
        public string FunctionParameter { get; set; }
        public Nullable<bool> Deletedby { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DefaultValue { get; set; }
        public string DefaultColum { get; set; }
    
        public virtual HRMS_Rec_InputTableHD HRMS_Rec_InputTableHD { get; set; }
    }
}
