//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCATEGORY
    {
        public int TenentID { get; set; }
        public int COMPANYID { get; set; }
        public int CATID { get; set; }
        public string CATTYPE { get; set; }
        public string SHORTNAME { get; set; }
        public string CATNAME { get; set; }
        public string CATNAMEO { get; set; }
        public string CATNAMECH { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
