//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICGRNTRCOST_HD
    {
        public int TenentID { get; set; }
        public long MYTRANSID { get; set; }
        public int OVERHEADID { get; set; }
        public long MYID { get; set; }
        public decimal AMOUNT { get; set; }
        public string NOTES { get; set; }
        public string ACCOUNTID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<decimal> COMPANY_SEQUENCE { get; set; }
    }
}
