//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICIT_BR_TMP
    {
        public int TenentID { get; set; }
        public long MyProdID { get; set; }
        public string period_code { get; set; }
        public string MySysName { get; set; }
        public int UOM { get; set; }
        public int SIZECODE { get; set; }
        public int COLORID { get; set; }
        public int Bin_ID { get; set; }
        public string BatchNo { get; set; }
        public string Serial_Number { get; set; }
        public long MYTRANSID { get; set; }
        public int LocationID { get; set; }
        public Nullable<decimal> NewQty { get; set; }
        public decimal OpQty { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> QtyOut { get; set; }
        public Nullable<decimal> QtyConsumed { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public Nullable<decimal> QtyReserved { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string Reference { get; set; }
        public string RecodName { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> LeadDays2Destroy { get; set; }
        public string Active { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<bool> MinusAllow { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
