//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICIT_BR_ReferenceNo
    {
        public int TenentID { get; set; }
        public string RefType { get; set; }
        public int MYTRANSID { get; set; }
        public long RefID { get; set; }
        public int MySeq { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
