//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICProdDisplay
    {
        public int TenentID { get; set; }
        public long MYPRODID { get; set; }
        public long Display_Id { get; set; }
        public string TableName { get; set; }
        public int REFID { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public Nullable<int> sortnumber { get; set; }
        public Nullable<int> PLACEHOLDERLINE { get; set; }
        public Nullable<int> PLACEHOLDERCOLUMN { get; set; }
        public Nullable<int> PLACEHOLDERALIRL { get; set; }
        public string LINK2DIRECT { get; set; }
        public Nullable<bool> ACTIVE2 { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
