//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICSUBCATEGORY
    {
        public int COMPANYID { get; set; }
        public int SUBCATID { get; set; }
        public string SUBCATTYPE { get; set; }
        public string SHORTNAME { get; set; }
        public string SUBCATNAME { get; set; }
        public string SUBCATNAMEO { get; set; }
        public string SUBCATNAMEO2 { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CATID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
