//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICTR_DT_Sales
    {
        public int TenentID { get; set; }
        public int locationID { get; set; }
        public int TerminalID { get; set; }
        public long MYTRANSID { get; set; }
        public int MYID { get; set; }
        public Nullable<long> MyProdID { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public string PERIOD_CODE { get; set; }
        public string MYSYSNAME { get; set; }
        public Nullable<int> JOID { get; set; }
        public Nullable<int> JOBORDERDTMYID { get; set; }
        public Nullable<int> ACTIVITYID { get; set; }
        public string DESCRIPTION { get; set; }
        public string UOM { get; set; }
        public decimal QUANTITY { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
        public Nullable<decimal> AvgCostAmount { get; set; }
        public Nullable<decimal> OVERHEADAMOUNT { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> CommAmtTot { get; set; }
        public string BATCHNO { get; set; }
        public Nullable<int> BIN_ID { get; set; }
        public string BIN_TYPE { get; set; }
        public string GRNREF { get; set; }
        public Nullable<decimal> DISPER { get; set; }
        public Nullable<decimal> DISAMT { get; set; }
        public Nullable<decimal> TAXPER { get; set; }
        public Nullable<decimal> TAXAMT { get; set; }
        public Nullable<decimal> PROMOTIONAMT { get; set; }
        public string SWITCH1 { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string ITEMID { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public string Stutas { get; set; }
        public Nullable<int> ConfirmQty { get; set; }
        public Nullable<int> DeliveredQTy { get; set; }
        public Nullable<int> LoyalityDis { get; set; }
        public Nullable<decimal> LoyalityAMT { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string GLPOST { get; set; }
        public string GLPOST1 { get; set; }
        public string GLPOSTREF1 { get; set; }
        public string GLPOSTREF { get; set; }
        public string ICPOST { get; set; }
        public string ICPOSTREF { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string SyncBy { get; set; }
        public Nullable<int> SynID { get; set; }
        public string tall { get; set; }
        public string Shoulder { get; set; }
        public string Sleeve { get; set; }
        public string Note { get; set; }
        public string CustItemCode { get; set; }
        public string Color { get; set; }
        public string Remarks { get; set; }
    }
}
