//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICTR_MYTRANSID
    {
        public int TenentID { get; set; }
        public int MYTRANSID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
    }
}
