//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICUOM
    {
        public int TenentID { get; set; }
        public int UOM { get; set; }
        public string UOMNAMESHORT { get; set; }
        public string UOMNAME1 { get; set; }
        public string UOMNAME2 { get; set; }
        public string UOMNAME3 { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string Active { get; set; }
        public string UOMNAME { get; set; }
        public string UOMNAMEO { get; set; }
        public string UOM_TYPE { get; set; }
        public Nullable<bool> MultiUOMAllow { get; set; }
        public Nullable<bool> CalculateAspectRatio { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
