//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSearchDetail
    {
        public int ID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> REFID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<decimal> ContactID { get; set; }
    
        public virtual TBLCOMPANYSETUP TBLCOMPANYSETUP { get; set; }
        public virtual TBLCONTACT TBLCONTACT { get; set; }
    }
}
