//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Portle_compnyService
    {
        public int Service_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Service_name { get; set; }
        public Nullable<int> Server_IconCode { get; set; }
        public string Server_Contact { get; set; }
    }
}
