//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Portal_ResumeEducation
    {
        public int InstiID { get; set; }
        public int ResumeID { get; set; }
        public string InstiName { get; set; }
        public string InstiQalification { get; set; }
        public Nullable<int> InstiPStart { get; set; }
        public Nullable<int> InstiPEnd { get; set; }
        public string InstiLocation { get; set; }
        public string InstiNote { get; set; }
    }
}
