//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Portal_CompanyTestimonial
    {
        public int Testimonial_Id { get; set; }
        public string Testimonial_Name { get; set; }
        public string Testimonial_organization { get; set; }
        public string Testimonial { get; set; }
        public string Testimonial_Avtar { get; set; }
    }
}
