//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Portal_Resume
    {
        public int TenentID { get; set; }
        public decimal ResumeID { get; set; }
        public Nullable<int> CONTACTID { get; set; }
        public string PHYSICALLOCID { get; set; }
        public string PersName1 { get; set; }
        public string PersName2 { get; set; }
        public string PersName3 { get; set; }
        public string EMAIL1 { get; set; }
        public string MOBPHONE { get; set; }
        public string ITMANAGER { get; set; }
        public string ADDR1 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> GENDER { get; set; }
        public string IMG { get; set; }
        public string CLocation { get; set; }
        public string UResume { get; set; }
        public Nullable<int> TExperince { get; set; }
        public string Industry { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string RAboutUS { get; set; }
        public string SkillTitle { get; set; }
        public string SkillCarlvl { get; set; }
        public string SkillCommlvl { get; set; }
        public string SkillCommNote { get; set; }
        public string SkillOrglvl { get; set; }
        public string SkillOrgNote { get; set; }
        public string SkillJoblvl { get; set; }
        public string SkillJobRNote { get; set; }
        public string NativeLanguage { get; set; }
        public string Hobbie { get; set; }
        public string InstiName { get; set; }
        public string InstiQalification { get; set; }
        public Nullable<int> InstiPStart { get; set; }
        public Nullable<int> InstiPEnd { get; set; }
        public string InstiLocation { get; set; }
        public string InstiNote { get; set; }
        public Nullable<int> SalaryRAmount { get; set; }
        public Nullable<int> SalaryPer { get; set; }
        public Nullable<bool> SlyJTypeFlncr { get; set; }
        public Nullable<bool> SlyJTypePTime { get; set; }
        public Nullable<bool> SlyJTypeFTime { get; set; }
        public Nullable<bool> SlyJTypeIntShip { get; set; }
        public Nullable<bool> SlyJTypeVoluntry { get; set; }
        public string ContactADD { get; set; }
        public Nullable<decimal> ContactNumber { get; set; }
        public string ContactWebsite { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFacebook { get; set; }
        public string ContactLinkdIn { get; set; }
        public string ContactGoogle { get; set; }
        public string ContactTwitter { get; set; }
        public string ContactMapAdd { get; set; }
        public Nullable<int> ContactLatitude { get; set; }
        public Nullable<int> ContactLongitude { get; set; }
    }
}
