//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO_Draft_Main
    {
        public int D_ID { get; set; }
        public Nullable<int> FromLocation { get; set; }
        public Nullable<int> ToLocation { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<decimal> RecipeQty { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsLPO { get; set; }
    }
}
