//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO_Delivery_Detail
    {
        public int DetailID { get; set; }
        public Nullable<int> Delivery_ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
    }
}
