//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPO_Delivery_Main
    {
        public int DeliveryID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> LPOID { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
