//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int TenentID { get; set; }
        public int locationID { get; set; }
        public int MappingID { get; set; }
        public string EnglishDescription { get; set; }
        public string ArabicDescription { get; set; }
        public string OtherDescription { get; set; }
        public int Account_ID { get; set; }
        public Nullable<long> crupid { get; set; }
    }
}
