//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE_MAP
    {
        public int TenentID { get; set; }
        public int PRIVILEGE_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public int MODULE_ID { get; set; }
        public int MODULE_MAP_ID { get; set; }
        public int UserID { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public Nullable<int> TenantID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> MySerial { get; set; }
        public string ALL_FLAG { get; set; }
        public string ADD_FLAG { get; set; }
        public string MODIFY_FLAG { get; set; }
        public string DELETE_FLAG { get; set; }
        public string VIEW_FLAG { get; set; }
        public Nullable<int> SP1 { get; set; }
        public Nullable<int> SP2 { get; set; }
        public Nullable<int> SP3 { get; set; }
        public Nullable<int> SP4 { get; set; }
        public Nullable<int> SP5 { get; set; }
        public string SP1Name { get; set; }
        public string SP2Name { get; set; }
        public string SP3Name { get; set; }
        public string SP4Name { get; set; }
        public string SP5Name { get; set; }
        public string AppVer { get; set; }
        public Nullable<System.DateTime> AppVerDate { get; set; }
        public string DBVer { get; set; }
        public Nullable<System.DateTime> DBVerDate { get; set; }
    }
}
