//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYBU
    {
        public int TenentID { get; set; }
        public int BUSID { get; set; }
        public string BUSTYPE { get; set; }
        public string SHORTNAME { get; set; }
        public string BUSNAME1 { get; set; }
        public string BUSNAME2 { get; set; }
        public string BUSNAME3 { get; set; }
        public string SWITCH1 { get; set; }
        public string SWITCH2 { get; set; }
        public string SWITCH3 { get; set; }
        public string Remarks { get; set; }
        public string COMPANID { get; set; }
        public string BUSNAME { get; set; }
        public string BUSNAMEO { get; set; }
        public string BUSNAMCHIN { get; set; }
        public string BUSYPE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
