//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyBusEcom
    {
        public int TenentID { get; set; }
        public int BusinessID { get; set; }
        public int ProductID { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
