//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCompaniySetup_Tryel
    {
        public int TenentID { get; set; }
        public int MyID { get; set; }
        public int LocationID { get; set; }
        public string CompanyName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> NumberofUser { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<bool> Deleteby { get; set; }
        public Nullable<bool> ActiveBy { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string crupID { get; set; }
        public string RetailerType { get; set; }
        public string WeSiteURL { get; set; }
        public string Password { get; set; }
        public string ProjectType { get; set; }
    }
}
