//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageFunctionSetup
    {
        public int ID { get; set; }
        public int FunMenuID { get; set; }
        public int PackageID { get; set; }
        public int InsertLimit { get; set; }
        public Nullable<bool> Deletedby { get; set; }
        public Nullable<bool> Activby { get; set; }
        public Nullable<int> Inserby { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
