//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeliveryMeal
    {
        public int TenentID { get; set; }
        public long LOCATION_ID { get; set; }
        public int CustomerID { get; set; }
        public int planid { get; set; }
        public string DeliveryTime { get; set; }
        public int MealID { get; set; }
        public string ShortRemark { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public byte[] ChangesDate { get; set; }
    }
}
