//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmeal
    {
        public int TenentID { get; set; }
        public long LOCATION_ID { get; set; }
        public int planid { get; set; }
        public int MealType { get; set; }
        public int UOM { get; set; }
        public Nullable<int> plandays { get; set; }
        public Nullable<bool> CustomAllow { get; set; }
        public string PlanInGram { get; set; }
        public string MealInGram { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public string plandesc { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<decimal> Carbs { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<decimal> PlanBasecost { get; set; }
        public Nullable<decimal> ItemBasecost { get; set; }
        public Nullable<decimal> ItemExtraCost { get; set; }
        public string ShortRemark { get; set; }
        public string MealFixFlexible { get; set; }
        public Nullable<int> MealAllowed { get; set; }
        public Nullable<int> TotalAllowed { get; set; }
        public Nullable<int> switch1 { get; set; }
        public string switch2 { get; set; }
        public string switch3 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> ChangesDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
