//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmealcustinvoiceMoreHD
    {
        public int TenentID { get; set; }
        public int MYTRANSID { get; set; }
        public string MealType { get; set; }
        public Nullable<int> planid { get; set; }
        public string Customized { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<int> TotalMealAllowed { get; set; }
        public Nullable<int> WeekMealAllowed { get; set; }
        public string PlanInGram { get; set; }
        public string MealFixFlexible { get; set; }
        public string MealInGram { get; set; }
        public Nullable<decimal> PlanBasecost { get; set; }
        public Nullable<decimal> ItemBasecost { get; set; }
        public Nullable<int> BaseMeal { get; set; }
        public Nullable<int> ExtraMeal { get; set; }
        public Nullable<decimal> ExtraMealCost { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<bool> AlloWeekend { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> AllWeekend { get; set; }
        public Nullable<int> PlanDays { get; set; }
    }
}
