//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_reclculate
    {
        public int TenentID { get; set; }
        public int recalculateid { get; set; }
        public int mytransid { get; set; }
        public Nullable<System.DateTime> reclculatedate { get; set; }
        public string status { get; set; }
        public Nullable<bool> successflag { get; set; }
    }
}
