//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmealsetupkitchen
    {
        public int TenentID { get; set; }
        public long LOCATION_ID { get; set; }
        public int planid { get; set; }
        public int MealType { get; set; }
        public int DayNumer { get; set; }
        public int serial_no { get; set; }
        public long MYPRODID { get; set; }
        public int UOM { get; set; }
        public long ProdNo { get; set; }
        public string DayName { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<decimal> Carbs { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<decimal> Item_cost { get; set; }
        public string ShortRemark { get; set; }
        public Nullable<int> KitchenWeek { get; set; }
        public Nullable<int> WeekOfYear { get; set; }
        public Nullable<int> MealRepeatInDay { get; set; }
        public Nullable<int> MealRepeatInWeek { get; set; }
        public Nullable<int> MealRepeatInMonth { get; set; }
        public Nullable<int> MealRepeatInYear { get; set; }
        public Nullable<int> Option1 { get; set; }
        public string Option2 { get; set; }
        public Nullable<int> Option3 { get; set; }
        public Nullable<System.DateTime> Option4 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
