//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class planmealcustinvoiceHD
    {
        public int TenentID { get; set; }
        public int MYTRANSID { get; set; }
        public long LOCATION_ID { get; set; }
        public int CustomerID { get; set; }
        public int planid { get; set; }
        public int DayNumber { get; set; }
        public Nullable<int> TransID { get; set; }
        public string ContractID { get; set; }
        public string WeekofDay { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<bool> AllowWeekend { get; set; }
        public Nullable<int> TotalSubDays { get; set; }
        public Nullable<int> DeliveredDays { get; set; }
        public Nullable<System.DateTime> NExtDeliveryDate { get; set; }
        public Nullable<int> NExtDeliveryNum { get; set; }
        public Nullable<int> Week1Count { get; set; }
        public Nullable<int> Week1TotalCount { get; set; }
        public Nullable<int> Week2Count { get; set; }
        public Nullable<int> Week2TotalCount { get; set; }
        public Nullable<int> Week3Count { get; set; }
        public Nullable<int> Week3TotalCount { get; set; }
        public Nullable<int> Week4Count { get; set; }
        public Nullable<int> Week4TotalCount { get; set; }
        public Nullable<int> Week5Count { get; set; }
        public Nullable<int> Week5TotalCount { get; set; }
        public Nullable<int> ContractSelectedCount { get; set; }
        public Nullable<int> ContractTotalCount { get; set; }
        public Nullable<bool> IsFullPlanCopied { get; set; }
        public Nullable<bool> SubscriptionOnHold { get; set; }
        public Nullable<System.DateTime> HoldDate { get; set; }
        public Nullable<System.DateTime> UnHoldDate { get; set; }
        public Nullable<int> Holdbyuser { get; set; }
        public string HoldREmark { get; set; }
        public Nullable<int> SubscriptonDayNumber { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public string PaymentStatus { get; set; }
        public int LocalID { get; set; }
        public string OfflineStatus { get; set; }
        public string Allergies { get; set; }
        public Nullable<int> Carbs { get; set; }
        public Nullable<int> Protein { get; set; }
        public string Remarks { get; set; }
        public string ShortRemark { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> ChangesDate { get; set; }
        public Nullable<int> DefaultDriverID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string CStatus { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string syncStatus { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
