//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSCompSetup
    {
        public int TenentID { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Terminalid { get; set; }
        public Nullable<int> Locationid { get; set; }
        public Nullable<int> Kitchen { get; set; }
        public Nullable<int> Module_Name { get; set; }
        public Nullable<int> Delivery_Location { get; set; }
        public Nullable<int> Payment_Days { get; set; }
        public Nullable<int> Reminder_Days { get; set; }
        public Nullable<bool> Desc_with_warrantee { get; set; }
        public Nullable<bool> Desc_with_serial { get; set; }
        public Nullable<bool> Desc_with_color { get; set; }
        public Nullable<bool> Allow_Minus_Qty { get; set; }
        public string Salesadmin_name { get; set; }
        public string Delivery_print_Url { get; set; }
        public string Counter_Name { get; set; }
        public string Header_Line { get; set; }
        public string Bottom_Tag_Line { get; set; }
        public string Payment_Details { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Defaultpic { get; set; }
        public string CashierPrinter1 { get; set; }
        public string DriverbyUs { get; set; }
        public Nullable<int> Country_name { get; set; }
        public string Tag_line { get; set; }
    }
}
