//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSSetting
    {
        public int ID { get; set; }
        public int TenentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Checkname { get; set; }
    }
}
