//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Cat_Mst
    {
        public int TenentID { get; set; }
        public long MYPRODID { get; set; }
        public int CATID { get; set; }
        public int PARENT_CATID { get; set; }
        public int UOM { get; set; }
        public string CATID_name { get; set; }
        public string PARENT_CATIDname { get; set; }
        public string BarCode { get; set; }
        public string Remarks { get; set; }
        public string Active { get; set; }
        public string DefaultProduct { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
