//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseProduct
    {
        public int SrID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> locationID { get; set; }
        public Nullable<int> MytransID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
