//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        public QuestionMaster()
        {
            this.RowMasters = new HashSet<RowMaster>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Perent_QID { get; set; }
        public string QuestionLang1 { get; set; }
        public string QuestionLang2 { get; set; }
        public string QuestionLang3 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Avtive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> ChoiseType { get; set; }
        public string Choise { get; set; }
        public Nullable<int> Choise1 { get; set; }
        public Nullable<int> Choise2 { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> Answer1 { get; set; }
        public Nullable<int> Answer2 { get; set; }
        public string Weitage { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BeforeQID { get; set; }
        public Nullable<int> AfterQID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> answerid { get; set; }
    
        public virtual ICollection<RowMaster> RowMasters { get; set; }
    }
}
