//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefLabelMST
    {
        public int TenentID { get; set; }
        public int RefLabelID { get; set; }
        public string RefType { get; set; }
        public string RefSubType { get; set; }
        public string LE1 { get; set; }
        public string LE2 { get; set; }
        public string LE3 { get; set; }
        public string LE4 { get; set; }
        public string LE5 { get; set; }
        public string LE6 { get; set; }
        public string LE7 { get; set; }
        public string LE8 { get; set; }
        public string LE9 { get; set; }
        public string LE10 { get; set; }
        public string LF1 { get; set; }
        public string LF2 { get; set; }
        public string LF3 { get; set; }
        public string LF4 { get; set; }
        public string LF5 { get; set; }
        public string LF6 { get; set; }
        public string LF7 { get; set; }
        public string LF8 { get; set; }
        public string LF9 { get; set; }
        public string LF10 { get; set; }
        public string LA1 { get; set; }
        public string LA2 { get; set; }
        public string LA3 { get; set; }
        public string LA4 { get; set; }
        public string LA5 { get; set; }
        public string LA6 { get; set; }
        public string LA7 { get; set; }
        public string LA8 { get; set; }
        public string LA9 { get; set; }
        public string LA10 { get; set; }
    }
}
