//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowMaster
    {
        public int ID { get; set; }
        public string RowNameAnswer { get; set; }
        public Nullable<int> ContactComapnyID { get; set; }
        public Nullable<int> AnswerBy { get; set; }
        public Nullable<System.DateTime> AnsDateTime { get; set; }
        public Nullable<int> QuestionBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Waitage { get; set; }
        public Nullable<bool> Answer { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> OptionMasterID { get; set; }
        public Nullable<int> QuetionID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    
        public virtual OptionMaster OptionMaster { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
