//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMan
    {
        public int SaleManID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> SaleManCode { get; set; }
        public string SaleManName { get; set; }
    }
}
