//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Item_OrderTotal
    {
        public int TenentID { get; set; }
        public int sales_id { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
