//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int ID { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> Senddate { get; set; }
    }
}
