//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Transfer_Main
    {
        public int TransferID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public string Reference { get; set; }
        public string Note { get; set; }
        public Nullable<int> FromLocation { get; set; }
        public Nullable<int> ToLocation { get; set; }
        public Nullable<int> DraftID { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Status { get; set; }
    }
}
