//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubHead
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int SubHeadID { get; set; }
        public int Head_ID { get; set; }
        public int SubHeadCode { get; set; }
        public string SubHeadName { get; set; }
        public string ArabicSubHeadName { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> crupid { get; set; }
        public Nullable<int> CrFlag { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
    }
}
