//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSubHead
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int SubSubHeadID { get; set; }
        public Nullable<int> SubHead_ID { get; set; }
        public Nullable<int> Head_ID { get; set; }
        public Nullable<long> SubSubHeadCode { get; set; }
        public string SubSubHeadName { get; set; }
        public string ArabicSubSubHeadName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> crupid { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
    }
}
