//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Event_Detail
    {
        public int TenantID { get; set; }
        public int EventID { get; set; }
        public int MyID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> EventTopic { get; set; }
        public string RegisterationIDBegin { get; set; }
        public Nullable<int> RegisterationNumber { get; set; }
        public string Title2Print { get; set; }
        public string RegURL { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> DMSid { get; set; }
        public Nullable<int> SocMediaID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> FloorPlanID { get; set; }
        public Nullable<int> eMailTemplateID { get; set; }
        public string KeyWord { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> ForcastedVisitor { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string ActivatedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
