//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_JobMst
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobPresence { get; set; }
        public Nullable<int> JobExperience { get; set; }
        public string JobDomain { get; set; }
        public string JobSubDomain { get; set; }
        public string JobType { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> JCountry { get; set; }
        public string JobOffer { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public Nullable<int> JobLocation { get; set; }
        public string JobCareerLevel { get; set; }
        public string JobDescription { get; set; }
        public string JobImage { get; set; }
        public string ComName { get; set; }
        public string ComWebsite { get; set; }
        public Nullable<decimal> ComContact { get; set; }
        public Nullable<int> ComSize { get; set; }
        public string ComJobDomain { get; set; }
        public string ComJobSubDomain { get; set; }
        public string ComRole { get; set; }
        public Nullable<int> ComIndustry { get; set; }
        public Nullable<System.DateTime> ComFromDate { get; set; }
        public Nullable<System.DateTime> ComTillDate { get; set; }
        public string ComADD1 { get; set; }
        public string ComADD2 { get; set; }
        public string ComDesc { get; set; }
        public string SkillCommunicationLevel { get; set; }
        public string CommunicationNote { get; set; }
        public string SkillOrganisationalLevel { get; set; }
        public string OrganisationalNote { get; set; }
        public string SkillRelatedLevel { get; set; }
        public string RelatedNote { get; set; }
        public string Skills { get; set; }
        public string Skillvalue { get; set; }
        public string NativeLanguage { get; set; }
        public string LanguageName { get; set; }
        public Nullable<int> LanguageSpeaking { get; set; }
        public Nullable<int> LanguageUnderstand { get; set; }
        public Nullable<int> LanguageWriting { get; set; }
        public string AdditionalRequirements { get; set; }
        public Nullable<decimal> RemunerationAmount { get; set; }
        public string Per { get; set; }
        public Nullable<int> Currency { get; set; }
        public string BenefitName { get; set; }
        public string BenefitDescription { get; set; }
        public string ContactAddress { get; set; }
        public string ContactPhone { get; set; }
        public string ContactWebsite { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFacebook { get; set; }
        public string ContactLinkedIn { get; set; }
        public string ContactTwitter { get; set; }
        public string ContactGoogle { get; set; }
        public string ContactEmailRadio { get; set; }
        public string GoogleMapsAddress { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Colour1 { get; set; }
        public string Colour2 { get; set; }
        public string Colour3 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SJObID { get; set; }
    }
}
