//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompanyTestimonial
    {
        public int TestID { get; set; }
        public int CompanyID { get; set; }
        public string TFullName { get; set; }
        public string Testimonial { get; set; }
        public string Organisation { get; set; }
        public string Avtar { get; set; }
        public Nullable<bool> ActivedBy { get; set; }
        public Nullable<bool> DeletedBy { get; set; }
    }
}
