//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tender
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int TenderID { get; set; }
        public string TenderUserRef { get; set; }
        public string TenderTitle { get; set; }
        public string Version { get; set; }
        public Nullable<int> TenderType { get; set; }
        public Nullable<int> PreparedByemp_id { get; set; }
        public Nullable<int> DMS_id { get; set; }
        public Nullable<int> TenderInudstryFor { get; set; }
        public Nullable<int> TenderStyle { get; set; }
        public Nullable<System.DateTime> TenderDate { get; set; }
        public Nullable<System.DateTime> TentitiveDate { get; set; }
        public Nullable<System.DateTime> LastSubmitDate { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> TenderFeeAmount { get; set; }
        public Nullable<decimal> TenderAmount { get; set; }
        public string Description { get; set; }
        public Nullable<int> TenderStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CeatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
