//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pay_Grade
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int GradeID { get; set; }
        public string GradeType { get; set; }
        public string GradeName1 { get; set; }
        public string GradeName2 { get; set; }
        public string GradeName3 { get; set; }
        public Nullable<decimal> SalaryStart { get; set; }
        public Nullable<decimal> SalaryEnd { get; set; }
        public Nullable<decimal> ExtraAmountPercentage { get; set; }
        public Nullable<decimal> PFCeizeAmount { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<decimal> PFPercentage { get; set; }
        public Nullable<int> TaxTemplate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
