//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Lead_Mst
    {
        public int TenentID { get; set; }
        public int ID { get; set; }
        public int Conact_id { get; set; }
        public string Customer_Name { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> Oppertunity_ID { get; set; }
        public Nullable<int> Campaign_ID { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> NoteID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> EmailIDAction { get; set; }
        public Nullable<int> MemoID { get; set; }
        public string Salutation { get; set; }
        public string Title { get; set; }
        public string TwitterScreenName { get; set; }
        public string Refered_by { get; set; }
        public Nullable<int> lead_source { get; set; }
        public Nullable<int> Status { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Do_not_call { get; set; }
        public string Assistant { get; set; }
        public string Assistant_phone { get; set; }
        public Nullable<bool> email_opt_out { get; set; }
        public Nullable<bool> invalid_email { get; set; }
        public string account_name { get; set; }
        public string opportunity_name { get; set; }
        public Nullable<decimal> opportunity_amount { get; set; }
        public string campaign_name { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string status_description { get; set; }
        public string description { get; set; }
        public string account_description { get; set; }
        public Nullable<int> team_name { get; set; }
        public string lead_source_description { get; set; }
        public string assigned_to_name { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Website { get; set; }
        public Nullable<bool> SMS_Opt_In { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string NoofEmployees { get; set; }
        public string LeadName1 { get; set; }
        public string LeadName2 { get; set; }
        public string LeadName3 { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string LeadSourcefrom { get; set; }
        public Nullable<int> StatusoftheLead { get; set; }
        public Nullable<int> PerformingDept { get; set; }
        public string TeamLeaderName { get; set; }
        public string ContactPerson { get; set; }
        public string Type { get; set; }
        public Nullable<int> RefNO { get; set; }
        public Nullable<int> SearchTitle { get; set; }
        public Nullable<int> QuestionGroup { get; set; }
        public Nullable<int> AppointmentID { get; set; }
    }
}
