//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StepsTable
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public string RouteID { get; set; }
        public int ActivityId { get; set; }
        public int SeqNo { get; set; }
        public int DocID { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public Nullable<int> F6 { get; set; }
        public Nullable<int> F7 { get; set; }
        public Nullable<int> F8 { get; set; }
        public Nullable<int> F9 { get; set; }
        public Nullable<int> F10 { get; set; }
        public Nullable<System.DateTime> F11 { get; set; }
        public Nullable<System.DateTime> F12 { get; set; }
        public Nullable<System.DateTime> F13 { get; set; }
        public Nullable<System.DateTime> F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
        public string F20 { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CRUPID { get; set; }
        public Nullable<System.DateTime> MyDateTime { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> Submitdate { get; set; }
        public string SignBy { get; set; }
        public Nullable<System.DateTime> Signdate { get; set; }
        public string RecBy { get; set; }
        public Nullable<System.DateTime> Recdate { get; set; }
        public string RecSignBy { get; set; }
        public Nullable<System.DateTime> RecSigndate { get; set; }
        public Nullable<bool> Submit_stutas { get; set; }
        public Nullable<bool> SubSign_stutas { get; set; }
        public Nullable<bool> Rec_stutas { get; set; }
        public Nullable<bool> RecSign_stutas { get; set; }
    }
}
