//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category_Master
    {
        public tbl_Category_Master()
        {
            this.tbl_Event_Master = new HashSet<tbl_Event_Master>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<tbl_Event_Master> tbl_Event_Master { get; set; }
    }
}
