//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Applicant_Language
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int AppID { get; set; }
        public int DescID { get; set; }
        public int MyID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CruipID { get; set; }
        public Nullable<int> Understanding { get; set; }
        public Nullable<int> Speaking { get; set; }
        public Nullable<int> Writing { get; set; }
        public Nullable<int> Reading { get; set; }
    }
}
