//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ISSearchUser_Master
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int SearchID { get; set; }
        public int userID { get; set; }
        public bool Allow { get; set; }
    }
}
