//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Running
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CourseManagementNo { get; set; }
        public int InstructorContactMyID { get; set; }
        public int Myid { get; set; }
        public int coordinatoremp_id { get; set; }
        public Nullable<System.DateTime> StDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string InstructorRemarks { get; set; }
        public Nullable<int> CourseStatus { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
