//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Coordinator
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CourseManagementNo { get; set; }
        public int coordinatoremp_id { get; set; }
        public int MYID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> assignedbyemp_id { get; set; }
        public Nullable<int> DMS_id { get; set; }
        public Nullable<int> CeatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
