//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Custom_Fields
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int ID { get; set; }
        public int field_num { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string screen { get; set; }
        public string extra_data { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
