//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INVOICE
    {
        public int TenentID { get; set; }
        public int invid { get; set; }
        public string customer_name { get; set; }
        public string country { get; set; }
        public string contact_person { get; set; }
        public string ref_no { get; set; }
        public string invoice_no { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> total { get; set; }
        public string userid { get; set; }
        public string batchid { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> ShippingStatus { get; set; }
        public Nullable<int> AssignDriver { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string PaymentStatus { get; set; }
    }
}
