//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Multi_Color_Size_Mst
    {
        public int TenentID { get; set; }
        public string RecordType { get; set; }
        public int RecTypeID { get; set; }
        public int CompniyAndContactID { get; set; }
        public int RunSerial { get; set; }
        public Nullable<int> Recource { get; set; }
        public string RecValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RecourceName { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
