//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Applicant_WorkExp
    {
        public int AppID { get; set; }
        public int WorkExpID { get; set; }
        public int COMPID { get; set; }
        public string WorkOrgName { get; set; }
        public string WorkJobPoss { get; set; }
        public Nullable<System.DateTime> WorkPStart { get; set; }
        public Nullable<System.DateTime> WorkPEnd { get; set; }
        public string WorkJobType { get; set; }
        public string WorkNote { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> ActivedBy { get; set; }
        public Nullable<bool> DeletedBy { get; set; }
    }
}
