//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Receipe
    {
        public int TenentID { get; set; }
        public int recNo { get; set; }
        public string Prefix { get; set; }
        public string RecType { get; set; }
        public string Receipe_English { get; set; }
        public string Receipe_Arabic { get; set; }
        public Nullable<decimal> ProdDays { get; set; }
        public string ExpireDays { get; set; }
        public Nullable<int> HourToComplate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
