//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompanyMst
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CompanyID { get; set; }
        public int JobID { get; set; }
        public string CompanyName { get; set; }
        public string TagLine { get; set; }
        public string Foundation_Year { get; set; }
        public Nullable<int> TeamSize { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Location { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public string CoverImage { get; set; }
        public string T_JobTitle { get; set; }
        public Nullable<int> T_JobLocation { get; set; }
        public string CJobDomain { get; set; }
        public string CJobSubDomain { get; set; }
        public Nullable<int> CarrierObjective { get; set; }
        public Nullable<int> T_Industry { get; set; }
        public Nullable<int> EmploymentType { get; set; }
        public Nullable<int> T_Country { get; set; }
        public Nullable<int> T_LastMonthlySalary { get; set; }
        public Nullable<int> emp_status { get; set; }
        public string WorkCompanyName { get; set; }
        public string WorkCompanyWebsite { get; set; }
        public Nullable<decimal> WorkCompanyNumber { get; set; }
        public string WorkCompanyDesc { get; set; }
        public string Service_Name { get; set; }
        public string ServiceContent { get; set; }
        public string ServiceIconCode { get; set; }
        public string Expertise { get; set; }
        public string ClientName { get; set; }
        public string ContractedForDoing { get; set; }
        public Nullable<int> ClientPeriodIN { get; set; }
        public Nullable<int> ClientPeriodOUT { get; set; }
        public string ClientNotes { get; set; }
        public string ClientsWebsite { get; set; }
        public string TestFullName { get; set; }
        public string TestOrganisation { get; set; }
        public string TestTestimonial { get; set; }
        public string TestPicture { get; set; }
        public string Address { get; set; }
        public string Facebook { get; set; }
        public Nullable<decimal> Phonenumber { get; set; }
        public string LinkedIn { get; set; }
        public string Website { get; set; }
        public string Twitter { get; set; }
        public string Email { get; set; }
        public string Google { get; set; }
        public Nullable<int> Emailradio { get; set; }
        public string GoogleMaps { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Active { get; set; }
        public string Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TestID { get; set; }
    }
}
