//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompanyService
    {
        public int ServiceID { get; set; }
        public int CompanyID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> IconCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ActiveBy { get; set; }
        public Nullable<bool> DeletedBy { get; set; }
    }
}
