//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Applicant_payType
    {
        public int Pay_id { get; set; }
        public int AppID { get; set; }
        public string Pay_name { get; set; }
        public System.DateTime DateStamp { get; set; }
        public Nullable<int> SecurityCode { get; set; }
    }
}
