//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kpi
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int BranchId { get; set; }
        public int id { get; set; }
        public Nullable<int> job_title_code { get; set; }
        public string Department { get; set; }
        public string KPI { get; set; }
        public Nullable<int> KPIGroupID { get; set; }
        public string description { get; set; }
        public Nullable<decimal> rate_min { get; set; }
        public Nullable<decimal> rate_max { get; set; }
        public Nullable<bool> DefaultScale { get; set; }
        public Nullable<int> rate_default { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
