//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SkillEducation
    {
        public int DescID { get; set; }
        public string RecType { get; set; }
        public string DescType { get; set; }
        public string DescName1 { get; set; }
        public string DescName2 { get; set; }
        public string DescName3 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
