//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_route
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public string RouteID { get; set; }
        public string RouteName1 { get; set; }
        public string RouteName2 { get; set; }
        public string RouteName3 { get; set; }
        public Nullable<int> TotalSeq { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> Days2Complete { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CrupId { get; set; }
        public string MyStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> PrintSignYes { get; set; }
        public Nullable<int> PrintSignSeq { get; set; }
        public string FieldName { get; set; }
        public string DefaultValue { get; set; }
    }
}
