//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job_Candidate
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int BranchId { get; set; }
        public int JobCandidateID { get; set; }
        public Nullable<int> AppID { get; set; }
        public int status { get; set; }
        public string comment { get; set; }
        public int mode_of_application { get; set; }
        public System.DateTime date_of_application { get; set; }
        public Nullable<int> cv_file_id { get; set; }
        public string cv_text_version { get; set; }
        public string keywords { get; set; }
        public Nullable<int> added_person { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
