//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Production
    {
        public int ProductionDetailID { get; set; }
        public int ProductionID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string IOSwitch { get; set; }
        public Nullable<int> DemandQty { get; set; }
        public Nullable<decimal> RequiredQty { get; set; }
    }
}
