//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuickLink
    {
        public int ID { get; set; }
        public int TenentID { get; set; }
        public int UserID { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string Menu_Location { get; set; }
        public string MenuName { get; set; }
        public string LinkURL { get; set; }
        public string Colour { get; set; }
    }
}
