//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Applicant_SOJobDesc
    {
        public string DomainId { get; set; }
        public string SubDomainId { get; set; }
        public string JobId { get; set; }
        public string JobName1 { get; set; }
        public string JobName2 { get; set; }
        public string JobName3 { get; set; }
        public string JobDescription1 { get; set; }
        public string JobDescription2 { get; set; }
        public string JobDescription3 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
