//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course_Running_dtl
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CourseManagementNo { get; set; }
        public int InstructorContactMyID { get; set; }
        public int Studentemp_id { get; set; }
        public Nullable<int> CourseDay { get; set; }
        public int MYID { get; set; }
        public Nullable<int> coordinatoremp_id { get; set; }
        public Nullable<System.DateTime> CourseDate { get; set; }
        public Nullable<System.DateTime> ActualDatein { get; set; }
        public Nullable<System.DateTime> ActualDateOut { get; set; }
        public string StudentRemarks { get; set; }
        public string CourseDayStatus { get; set; }
        public string StudentStatus { get; set; }
        public Nullable<long> CruipID { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
