//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompanyClient
    {
        public int ClientID { get; set; }
        public int CompanyID { get; set; }
        public string ClientName { get; set; }
        public string ClientWebsite { get; set; }
        public Nullable<int> PeriodIn { get; set; }
        public Nullable<int> PeriodOut { get; set; }
        public string ContractDoing { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ActivedBy { get; set; }
        public Nullable<bool> DeletedBy { get; set; }
    }
}
