//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Flow
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int FlowID { get; set; }
        public string reference { get; set; }
        public int NextFlowID { get; set; }
        public string FlowShortName { get; set; }
        public int FlowSeq { get; set; }
        public string FlowName1 { get; set; }
        public string FlowName2 { get; set; }
        public string FlowName3 { get; set; }
        public string FlowDescription { get; set; }
        public Nullable<int> FlowOutByID { get; set; }
        public Nullable<int> From_ID { get; set; }
        public string FromName { get; set; }
        public Nullable<bool> SendOutSign { get; set; }
        public Nullable<int> OutSignby_ID { get; set; }
        public Nullable<System.DateTime> OutStartDate { get; set; }
        public Nullable<int> FlowInToByID { get; set; }
        public Nullable<int> ToReceiving_ID { get; set; }
        public string ToReceivingName { get; set; }
        public Nullable<bool> RecSign { get; set; }
        public Nullable<int> RecSignby_ID { get; set; }
        public Nullable<System.DateTime> RecStartDate { get; set; }
        public Nullable<int> DMS_id { get; set; }
        public int CompletionInDays { get; set; }
        public string NotificationEmail { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
