//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeeBenefit
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int EmpID { get; set; }
        public int BenefitID { get; set; }
        public string eligibility { get; set; }
        public Nullable<bool> AddWithSalary { get; set; }
        public Nullable<decimal> BenefitAmount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Note { get; set; }
        public string coverage { get; set; }
        public Nullable<int> id_emp_benefits { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
