//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job_Vacancy
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int BranchId { get; set; }
        public int Vacancy_ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public int job_title_code { get; set; }
        public Nullable<int> hiring_manager_id { get; set; }
        public Nullable<int> SubUnitID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> no_of_positions { get; set; }
        public int status { get; set; }
        public bool published_in_feed { get; set; }
        public System.DateTime defined_time { get; set; }
        public System.DateTime updated_time { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
