//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Applicant_Training
    {
        public int AppId { get; set; }
        public int TrainingID { get; set; }
        public int LocationId { get; set; }
        public string Title { get; set; }
        public Nullable<int> TInstitute { get; set; }
        public Nullable<System.DateTime> StartMonth { get; set; }
        public Nullable<System.DateTime> StartYear { get; set; }
        public string TCertificate { get; set; }
        public Nullable<int> THours { get; set; }
        public Nullable<bool> ActivedBy { get; set; }
        public Nullable<bool> DeletedBy { get; set; }
        public Nullable<int> ResumeID { get; set; }
        public string Status { get; set; }
    }
}
