//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Education
    {
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public int EducationID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string EducationType { get; set; }
        public string EducationName1 { get; set; }
        public string EducationName2 { get; set; }
        public string EducationName3 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
