//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tender_Raised
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int TenderID { get; set; }
        public string TenderUserRef { get; set; }
        public int TenderSerial { get; set; }
        public int MYID { get; set; }
        public int CourseID { get; set; }
        public int CompID { get; set; }
        public Nullable<int> DMS_id { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<decimal> TenderFeeAmount { get; set; }
        public Nullable<decimal> TenderAmount { get; set; }
        public Nullable<int> TenderStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CeatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<long> CruipID { get; set; }
    }
}
