//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DMSroute
    {
        public int TenentID { get; set; }
        public string RouteID { get; set; }
        public int REFID { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public int LineNum { get; set; }
        public int CompID { get; set; }
        public int ACTIVITYCODE { get; set; }
        public int SeqNo { get; set; }
        public int Days2Complete { get; set; }
        public int NextSeqNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FieldID { get; set; }
        public string Version { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string MyStatus { get; set; }
        public Nullable<int> User { get; set; }
    }
}
