//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusProd
    {
        public int TenentID { get; set; }
        public Nullable<long> LOCATION_ID { get; set; }
        public long MYPRODID { get; set; }
        public int REFID { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public long MYID { get; set; }
        public string MYTYPE { get; set; }
        public Nullable<System.DateTime> DISPDATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> HOTITEM { get; set; }
        public Nullable<long> DISPLAY_ID { get; set; }
        public Nullable<bool> ONLINESALEALLOW { get; set; }
        public Nullable<bool> DIRECTSALE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> SORTNUMBER { get; set; }
        public Nullable<int> PLACEHOLDERLINE { get; set; }
        public Nullable<int> PLACEHOLDERCOLUMN { get; set; }
        public Nullable<int> PLACEHOLDERALIRL { get; set; }
        public Nullable<bool> ONLINESALEALOW { get; set; }
        public string BUSNAME { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
    }
}
