//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCOMPANY_LOCATION
    {
        public int TenentID { get; set; }
        public string LOCATIONID { get; set; }
        public int COMPID { get; set; }
        public long RUNNINGSERIAL { get; set; }
        public string ACCOUNT { get; set; }
        public System.DateTime UPDTTIME { get; set; }
        public string LOCATION_NAME1 { get; set; }
        public string LOCATION_NAME2 { get; set; }
        public string LOCATION_NAME3 { get; set; }
        public string SHORTNAME { get; set; }
        public string LOCATION_ADDRESS { get; set; }
        public string LOCATION_PHONE { get; set; }
        public decimal EVENT_REMINDER_DAY { get; set; }
        public System.DateTime RUNNING_MONTH { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public string ACTIVE { get; set; }
        public System.DateTime ENTRYTIME { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
