//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCOLOR
    {
        public int TenentID { get; set; }
        public int COLORID { get; set; }
        public string COLORDESC1 { get; set; }
        public string COLORDESC2 { get; set; }
        public string COLORREMARKS { get; set; }
        public string hex { get; set; }
        public string RGB { get; set; }
        public string color { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string Active { get; set; }
    }
}
