//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT_DEL_ADRES
    {
        public int TenentID { get; set; }
        public decimal ContactMyID { get; set; }
        public int DeliveryAdressID { get; set; }
        public string GoogleName { get; set; }
        public string Latitute { get; set; }
        public string Longitute { get; set; }
        public Nullable<decimal> ContactID { get; set; }
        public string AdressShortName1 { get; set; }
        public string AdressName1 { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string Block { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string Lane { get; set; }
        public string ForFlat { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string CUSERID { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<System.DateTime> ENTRYTIME { get; set; }
        public Nullable<System.DateTime> UPDTTIME { get; set; }
        public string Active { get; set; }
        public Nullable<bool> Defualt { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string syncStatus { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> CompLoc { get; set; }
        public Nullable<int> PACKNumber { get; set; }
    }
}
