//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcontact_addon1_dtl
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int customerID { get; set; }
        public int myID { get; set; }
        public Nullable<int> LikeId { get; set; }
        public Nullable<int> planid { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> Allergy { get; set; }
        public string LikeType { get; set; }
        public Nullable<int> ComplinID { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> crupid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
