//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract_driver
    {
        public int TenentID { get; set; }
        public int locationid { get; set; }
        public int contactId { get; set; }
        public string invoiceid { get; set; }
        public Nullable<int> tripid { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Block { get; set; }
        public string GoogleName { get; set; }
        public string Latitute { get; set; }
        public string Longitute { get; set; }
        public string ContractID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public string PACINo { get; set; }
        public string DriverRemarks { get; set; }
        public Nullable<System.DateTime> tripDate { get; set; }
        public Nullable<System.DateTime> timedelivered { get; set; }
        public Nullable<int> finalstatus { get; set; }
        public string differentials { get; set; }
        public Nullable<int> crupid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string syncStatus { get; set; }
    }
}
