//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCONTACTBu
    {
        public int TenentID { get; set; }
        public int ContactMyID { get; set; }
        public int CompID { get; set; }
        public string PhysicalLocID { get; set; }
        public string Country { get; set; }
        public string JobTitle { get; set; }
        public string BusPhone1 { get; set; }
        public string email2 { get; set; }
        public string Fax { get; set; }
        public string PrimLanguge { get; set; }
        public string webpage { get; set; }
        public Nullable<bool> IsSMB { get; set; }
        public Nullable<bool> InHawally { get; set; }
        public Nullable<bool> emaiSub { get; set; }
        public Nullable<System.DateTime> EmailSubDate { get; set; }
        public Nullable<bool> saler { get; set; }
        public Nullable<bool> buyer { get; set; }
        public Nullable<bool> freelancer { get; set; }
        public Nullable<bool> saledeprod { get; set; }
        public string CUserID { get; set; }
        public string Cpasswrd { get; set; }
        public Nullable<System.DateTime> lastPassChanged { get; set; }
        public string Active { get; set; }
        public string remarks { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
