//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDriverDeliverystatu
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int CustomerId { get; set; }
        public string DeliveryCountry { get; set; }
        public string State { get; set; }
        public string Area { get; set; }
        public string DeliveryTime { get; set; }
        public string AdvCollectionStatus { get; set; }
        public string PromotionOn { get; set; }
        public Nullable<decimal> latituet { get; set; }
        public Nullable<decimal> longituet { get; set; }
        public string Height { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> crupid { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string agreedcabs { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
