//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGROUP_USER
    {
        public int TenentID { get; set; }
        public int LocationId { get; set; }
        public int ITGROUPID { get; set; }
        public string USERCODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> ACTIVE_Flag { get; set; }
        public string GROUPID { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
