//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgprsdata
    {
        public int TenentID { get; set; }
        public int UserID { get; set; }
        public int ID { get; set; }
        public string Date { get; set; }
        public string latitude { get; set; }
        public string logitude { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
