//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHelpDeskUserSet
    {
        public int TenentID { get; set; }
        public int USER_ID { get; set; }
        public int Location_ID { get; set; }
        public string AllowReOpen { get; set; }
        public string AllowNewTicket { get; set; }
        public string AllowDeleteTicket { get; set; }
        public string AllowPrint { get; set; }
        public string AllowPending { get; set; }
        public Nullable<bool> reopen { get; set; }
        public Nullable<bool> newticket { get; set; }
        public Nullable<bool> deleteticket { get; set; }
    }
}
