//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguage
    {
        public int TenentID { get; set; }
        public int MYCONLOCID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string LangName1 { get; set; }
        public string LangName2 { get; set; }
        public string LangName3 { get; set; }
        public string CULTUREOCDE { get; set; }
        public string ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
