//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLabelDTL
    {
        public int ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string LabelMstID { get; set; }
        public string FieldName { get; set; }
        public string LabelID { get; set; }
        public string LabelName { get; set; }
        public Nullable<int> LangID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string LANGDISP { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
