//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERIOD
    {
        public int TenentID { get; set; }
        public long PERIOD_CODE { get; set; }
        public string MYSYSNAME { get; set; }
        public short PRD_YEAR { get; set; }
        public string PRD_MONTH { get; set; }
        public string PRD_PERIOD1 { get; set; }
        public string PRD_PERIOD2 { get; set; }
        public string PRD_PERIOD3 { get; set; }
        public System.DateTime PRD_START_DATE { get; set; }
        public System.DateTime PRD_END_DATE { get; set; }
        public string GLPOST { get; set; }
        public string GLPOSTREF { get; set; }
        public string ICPOST { get; set; }
        public string ICPOSTREF { get; set; }
        public string STATUS1 { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string PRD_PERIOD { get; set; }
    }
}
