//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct_SubPlan
    {
        public int TenentID { get; set; }
        public int locationid { get; set; }
        public int planid { get; set; }
        public int SubPlanId { get; set; }
        public string Sub_planname1 { get; set; }
        public string Sub_planname2 { get; set; }
        public string Sub_planname3 { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<decimal> Sub_Plan_cost { get; set; }
        public Nullable<int> Sub_Plan_price1 { get; set; }
        public Nullable<int> Sub_Plan_price2 { get; set; }
        public Nullable<int> Sub_Plan_price3 { get; set; }
        public Nullable<int> ccount { get; set; }
        public string Sub_Plan_sale { get; set; }
        public Nullable<int> account { get; set; }
    }
}
