//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprod_feature
    {
        public int TenentID { get; set; }
        public int MyID { get; set; }
        public long Productid { get; set; }
        public string FeatureType { get; set; }
        public string FeatureImage { get; set; }
        public string Fetaures { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FeatureName { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
