//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSIZE
    {
        public int TenentID { get; set; }
        public int SIZECODE { get; set; }
        public string SIZETYPE { get; set; }
        public string SIZEDESC1 { get; set; }
        public string SIZEDESC2 { get; set; }
        public string SIZEDESC3 { get; set; }
        public string SIZEREMARKS { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string ACTIVE { get; set; }
    }
}
