//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSYSTEM
    {
        public int TenentID { get; set; }
        public int SystemID { get; set; }
        public string MYSYSNAME { get; set; }
        public string SYSDESC1 { get; set; }
        public string SYSDESC2 { get; set; }
        public string SYSDESC3 { get; set; }
        public string SHORTNAME { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string ACTIVE { get; set; }
        public string SYSDESC { get; set; }
        public string SYSDESCO { get; set; }
        public string SYSDESCCH { get; set; }
    }
}
