//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSenegalmain
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ArabicTitle { get; set; }
        public string Description { get; set; }
        public string ArabicDescription { get; set; }
        public string UCName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string avtar { get; set; }
        public Nullable<int> Seq_Order { get; set; }
        public Nullable<int> PageID { get; set; }
        public string HTMLData { get; set; }
        public string ArabicHTMLData { get; set; }
        public string PageType { get; set; }
    }
}
