//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSYSUSERBATCH
    {
        public string USERBATCHNO { get; set; }
        public string MYSYSNAME { get; set; }
        public string USERCODE { get; set; }
        public string STATUS1 { get; set; }
        public string ENTEREDBY { get; set; }
        public Nullable<System.DateTime> ENTEREDDATE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
