//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsetupPurchase
    {
        public int TenentID { get; set; }
        public int locationID { get; set; }
        public string module { get; set; }
        public string DeliveryLocation { get; set; }
        public string BottomTagLine { get; set; }
        public Nullable<int> CompniID { get; set; }
        public string LastClosePeriod { get; set; }
        public string CurrentPeriod { get; set; }
        public int PaymentDays { get; set; }
        public Nullable<int> ReminderDays { get; set; }
        public Nullable<int> AcceptWarantee { get; set; }
        public Nullable<bool> AutoGeneratePO { get; set; }
        public Nullable<bool> AutoGenerateGRN { get; set; }
        public Nullable<int> transid2 { get; set; }
        public Nullable<int> transsubid2 { get; set; }
        public Nullable<int> transid1 { get; set; }
        public Nullable<int> transsubid1 { get; set; }
        public Nullable<int> Created { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
