//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubscriber
    {
        public string EMAIL { get; set; }
        public string NAME1 { get; set; }
        public Nullable<bool> NEWSSUBSCRIBE { get; set; }
        public string NAME2 { get; set; }
        public string NAME3 { get; set; }
        public Nullable<bool> TODAYOFFERSUB { get; set; }
        public Nullable<System.DateTime> DATEREG { get; set; }
        public Nullable<System.DateTime> DATEUNREG { get; set; }
        public string REMARKS { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public string NAMEE { get; set; }
        public string NAMEA { get; set; }
        public string NAMECH { get; set; }
    }
}
