//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltranssubtype
    {
        public int TenentID { get; set; }
        public int transid { get; set; }
        public string MYSYSNAME { get; set; }
        public int transsubid { get; set; }
        public string transsubtype1 { get; set; }
        public string transsubtype2 { get; set; }
        public string transsubtype3 { get; set; }
        public string OpQtyBeh { get; set; }
        public string OnHandBeh { get; set; }
        public string QtyOutBeh { get; set; }
        public string QtyConsumedBeh { get; set; }
        public string QtyReservedBeh { get; set; }
        public string QtyAtDestination { get; set; }
        public string QtyAtSource { get; set; }
        public string serialno { get; set; }
        public string years { get; set; }
        public string Active { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public string transsubtype { get; set; }
        public string CashBeh { get; set; }
        public string QtyReceivedBeh { get; set; }
    }
}
