//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamName
    {
        public int TenentID { get; set; }
        public int LocationID { get; set; }
        public int TeamID { get; set; }
        public int REF_ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
