//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_AMPMMeal
    {
        public int MyID { get; set; }
        public int TenentID { get; set; }
        public Nullable<System.DateTime> ExpectedDelDate { get; set; }
        public Nullable<int> PlanID { get; set; }
        public Nullable<int> Meal { get; set; }
        public Nullable<int> DeliverTime { get; set; }
        public string Delivery { get; set; }
        public string TableName1 { get; set; }
        public Nullable<long> Product { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> TOTQTY { get; set; }
        public Nullable<int> NormalQty { get; set; }
        public Nullable<int> Qty150 { get; set; }
        public Nullable<int> Qty200 { get; set; }
        public Nullable<int> Qty250 { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> UOM { get; set; }
    }
}
