//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Job_ContactResume
    {
        public int ID { get; set; }
        public Nullable<int> TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ResumeID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> NoOfResume { get; set; }
        public Nullable<bool> IsApplicant { get; set; }
        public string path { get; set; }
        public Nullable<int> APPID { get; set; }
    }
}
