//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tempdatatable
    {
        public int TenentID { get; set; }
        public int Type { get; set; }
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<decimal> TotalCount { get; set; }
        public Nullable<decimal> percentage { get; set; }
    }
}
