//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ImageTable
    {
        public int TenentID { get; set; }
        public long MYPRODID { get; set; }
        public long ImageID { get; set; }
        public int ID { get; set; }
        public Nullable<int> sortnumber { get; set; }
        public string PICTURE { get; set; }
        public string Active { get; set; }
        public Nullable<int> SIZECODE { get; set; }
        public Nullable<int> COLORID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
