//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ISDepartment1
    {
        public int DepartmentID { get; set; }
        public int TenentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string DepartmentName1 { get; set; }
        public string DepartmentName2 { get; set; }
        public string DepartmentName3 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
