//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_BlogForum
    {
        public int ID { get; set; }
        public int TenentID { get; set; }
        public Nullable<int> ForumType { get; set; }
        public string ForumTopic { get; set; }
        public string ForumTopic2 { get; set; }
        public string ForumTopic3 { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Visited { get; set; }
        public string DisplayName { get; set; }
        public string Avtar { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
