//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempUser
    {
        public long TenentID { get; set; }
        public int PRIVILAGEID { get; set; }
        public string PRIVILAGESOURCE { get; set; }
        public int MENUID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> PRIVILAGE_MENUID { get; set; }
        public Nullable<int> MODULE_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string ADD_FLAG { get; set; }
        public string MODIFY_FLAG { get; set; }
        public string DELETE_FLAG { get; set; }
        public string VIEW_FLAG { get; set; }
        public Nullable<int> PRINTFLAGE { get; set; }
        public string ALL_FLAG { get; set; }
        public string LINK { get; set; }
        public Nullable<int> MASTER_ID { get; set; }
        public string MENU_TYPE { get; set; }
        public string MENU_NAME1 { get; set; }
        public string MENU_NAME2 { get; set; }
        public string MENU_NAME3 { get; set; }
        public string URLREWRITE { get; set; }
        public string MENU_LOCATION { get; set; }
        public Nullable<decimal> MENU_ORDER { get; set; }
        public string DOC_PARENT { get; set; }
        public Nullable<int> AMIGLOBALE { get; set; }
        public Nullable<int> MYPERSONAL { get; set; }
        public string SMALLTEXT { get; set; }
        public string ICONPATH { get; set; }
        public string METATITLE { get; set; }
        public string METAKEYWORD { get; set; }
        public string METADESCRIPTION { get; set; }
        public string HEADERVISIBLEDATA { get; set; }
        public string HEADERINVISIBLEDATA { get; set; }
        public string FOOTERVISIBLEDATA { get; set; }
        public string FOOTERINVISIBLEDATA { get; set; }
        public Nullable<int> REFID { get; set; }
        public Nullable<int> MYBUSID { get; set; }
        public Nullable<System.DateTime> ACTIVETILLDATE { get; set; }
        public Nullable<bool> ACTIVEMENU { get; set; }
        public Nullable<bool> ACTIVEPRIVILAGE { get; set; }
        public Nullable<bool> ACTIVEMODULE { get; set; }
        public Nullable<bool> ACTIVEROLE { get; set; }
        public Nullable<bool> URADD_FLAG { get; set; }
        public Nullable<bool> URMODIFY_FLAG { get; set; }
        public Nullable<bool> URDELETE_FLAG { get; set; }
        public Nullable<bool> URVIEW_FLAG { get; set; }
        public Nullable<bool> URALL_FLAG { get; set; }
        public Nullable<bool> IsLabelUpdate { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<int> SP1 { get; set; }
        public Nullable<int> SP2 { get; set; }
        public Nullable<int> SP3 { get; set; }
        public Nullable<int> SP4 { get; set; }
        public Nullable<int> SP5 { get; set; }
        public string SP1Name { get; set; }
        public string SP2Name { get; set; }
        public string SP3Name { get; set; }
        public string SP4Name { get; set; }
        public string SP5Name { get; set; }
    }
}
