//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDisplayEcomTable
    {
        public int TenentID { get; set; }
        public int MyID { get; set; }
        public System.DateTime DatePerf { get; set; }
        public Nullable<int> BusID { get; set; }
        public string BUSTYPE { get; set; }
        public string BusSUBTYPE { get; set; }
        public string REFNAME2 { get; set; }
        public long MYPRODID { get; set; }
        public int CATID { get; set; }
        public string CatName { get; set; }
        public Nullable<int> SubCatFound { get; set; }
        public Nullable<int> SubCatFoundAbove5 { get; set; }
        public int PARENT_CATID { get; set; }
        public string ParentCatName { get; set; }
        public Nullable<int> ProdFoundAbove5 { get; set; }
        public string Brand { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> NosInbrandFound { get; set; }
        public string BarCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> OfferProd { get; set; }
        public Nullable<bool> WebProd { get; set; }
        public string Active { get; set; }
        public string DefaultPic { get; set; }
        public Nullable<bool> IsStock { get; set; }
        public Nullable<bool> Sale { get; set; }
        public Nullable<bool> New { get; set; }
        public Nullable<bool> Size { get; set; }
        public Nullable<bool> Color { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> HotItem { get; set; }
        public Nullable<long> OfferID { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
