//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantGroup
    {
        public int MainTenantID { get; set; }
        public int TenentID { get; set; }
        public string COMPNAME1 { get; set; }
        public string COMPNAME2 { get; set; }
        public string COMPNAME3 { get; set; }
        public int COUNTRYID { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTALCODE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string ARABIC { get; set; }
        public decimal DECIMALCURRENCY { get; set; }
        public string REPORTDEFAULT { get; set; }
        public string REPORTDIRECTORY { get; set; }
        public string DATADIRECTORY { get; set; }
        public string BACKUPDIRECTORY { get; set; }
        public string EXECUTABLEDIRECTORY { get; set; }
        public string INVDATABASENAME { get; set; }
        public string ACTDATABASENAME { get; set; }
        public string Language1 { get; set; }
        public string Language2 { get; set; }
        public string Language3 { get; set; }
        public string USERID { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public System.DateTime ENTRYTIME { get; set; }
        public System.DateTime UPDTTIME { get; set; }
        public Nullable<int> REC_RUNNING_SRL { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
