//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public string First_name { get; set; }
        public string Address { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
    }
}
