//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RIGHTS
    {
        public int TenentID { get; set; }
        public int RIGHTS_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> PRIVILEGE_ID { get; set; }
        public bool ADD_FLAG { get; set; }
        public bool MODIFY_FLAG { get; set; }
        public bool DELETE_FLAG { get; set; }
        public bool VIEW_FLAG { get; set; }
        public bool ALL_FLAG { get; set; }
        public Nullable<long> CRUP_ID { get; set; }
        public Nullable<bool> IsLabelUpdate { get; set; }
        public Nullable<bool> SP1 { get; set; }
        public Nullable<bool> SP2 { get; set; }
        public Nullable<bool> SP3 { get; set; }
        public Nullable<bool> SP4 { get; set; }
        public Nullable<bool> SP5 { get; set; }
        public string SP1Name { get; set; }
        public string SP2Name { get; set; }
        public string SP3Name { get; set; }
        public string SP4Name { get; set; }
        public string SP5Name { get; set; }
        public string status { get; set; }
    }
}
