//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class veHDDTTran
    {
        public long PO_ { get; set; }
        public int POLine { get; set; }
        public Nullable<long> SystemItemID { get; set; }
        public string BarCode { get; set; }
        public string Part_No { get; set; }
        public string Alter2 { get; set; }
        public string UOMID { get; set; }
        public string UOM { get; set; }
        public string Brand { get; set; }
        public string Item_Description { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> US_Unit { get; set; }
        public Nullable<decimal> US_Amount { get; set; }
        public Nullable<decimal> KDUnitPrice { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public long MYTRANSID { get; set; }
        public int MYID { get; set; }
        public int TenentID { get; set; }
        public Nullable<int> transid { get; set; }
        public Nullable<int> transsubid { get; set; }
        public string MYSYSNAME { get; set; }
        public string MainTranType { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string TransDocNo { get; set; }
        public string TranType { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public int PaymentTermsId { get; set; }
        public string CounterID { get; set; }
        public Nullable<int> CashBankChequeID { get; set; }
        public Nullable<decimal> PayTermsAmount { get; set; }
        public string PayTermsReferenceNo { get; set; }
        public string PayTermsName { get; set; }
        public Nullable<System.DateTime> PayTermsTransDate { get; set; }
        public Nullable<System.DateTime> PayTermsCheckOutDate { get; set; }
        public string PaytermNote { get; set; }
        public Nullable<int> PayTermsAccountID { get; set; }
        public string SupplierName { get; set; }
    }
}
