//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vePrintPO16
    {
        public long PO_ { get; set; }
        public int POLine { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string BarCode { get; set; }
        public string Part_No { get; set; }
        public string Alter2 { get; set; }
        public string UOM { get; set; }
        public string Brand { get; set; }
        public string Item_Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> US_Unit { get; set; }
        public Nullable<decimal> US_Amount { get; set; }
        public Nullable<decimal> KDUnitPrice { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> SuggestedMSRP60_ { get; set; }
        public Nullable<decimal> P60 { get; set; }
        public Nullable<decimal> P50 { get; set; }
        public Nullable<decimal> P40 { get; set; }
        public Nullable<decimal> P30 { get; set; }
    }
}
