//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VieEatSmartPlanMealSetup
    {
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public int planid { get; set; }
        public string planname1 { get; set; }
        public int MealType { get; set; }
        public long MYPRODID { get; set; }
        public int PlanMealUOM { get; set; }
        public Nullable<int> ProductUOM { get; set; }
        public int KitchenUOM { get; set; }
        public string ProdName1 { get; set; }
        public string DayName { get; set; }
        public string DayNumer { get; set; }
        public Nullable<int> serial_no { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<decimal> Item_cost { get; set; }
        public Nullable<bool> KitActive { get; set; }
        public Nullable<bool> PMSActive { get; set; }
        public string ProdActive { get; set; }
    }
}
