//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer_product
    {
        public int TenentID { get; set; }
        public int COMPID { get; set; }
        public long MYPRODID { get; set; }
        public Nullable<int> UOM { get; set; }
        public string ProdName1 { get; set; }
        public string COMPNAME1 { get; set; }
        public Nullable<int> ProdTypeRefId { get; set; }
        public string CompanyType { get; set; }
    }
}
