//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Receipe_ManagementGrp
    {
        public int TenentID { get; set; }
        public int recNo { get; set; }
        public string IOSwitch { get; set; }
        public int ItemCode { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> ValueAmt { get; set; }
        public string RecType { get; set; }
    }
}
