//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GYMPrint
    {
        public int TenentID { get; set; }
        public Nullable<decimal> CUSTVENDID { get; set; }
        public int MYID { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> DISAMT { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public int locationID { get; set; }
        public string Stutas { get; set; }
        public string PersName1 { get; set; }
        public string BarCode { get; set; }
        public string ProdName1 { get; set; }
        public long MYTRANSID { get; set; }
        public Nullable<long> MyProdID { get; set; }
    }
}
