//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CompanyLikeAlergie
    {
        public int COMPID { get; set; }
        public string COMPNAME1 { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CivilID { get; set; }
        public string EMAIL { get; set; }
        public string ADDR1 { get; set; }
        public int COUNTRYID { get; set; }
        public string COUNAME1 { get; set; }
        public string MYNAME1 { get; set; }
        public string CityEnglish { get; set; }
        public string Active { get; set; }
        public int myID { get; set; }
        public Nullable<int> LikeId { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> Allergy { get; set; }
        public string LikeType { get; set; }
        public Nullable<int> ComplinID { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Remarks { get; set; }
    }
}
