//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SumPO
    {
        public Nullable<long> MyProdID { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int TenentID { get; set; }
    }
}
