//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CustomerListCountryCityState
    {
        public int COMPID { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CivilID { get; set; }
        public string EMAIL { get; set; }
        public string ADDR1 { get; set; }
        public string COUNAME1 { get; set; }
        public string State { get; set; }
        public string CityEnglish { get; set; }
        public string Active { get; set; }
    }
}
