//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RequestForm
    {
        public int TenentID { get; set; }
        public long MYTRANSID { get; set; }
        public int locationID { get; set; }
        public Nullable<int> transid { get; set; }
        public Nullable<int> transsubid { get; set; }
        public string MYSYSNAME { get; set; }
        public Nullable<decimal> COMPID { get; set; }
        public string UOM { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string COMPNAME1 { get; set; }
        public Nullable<long> MyProdID { get; set; }
    }
}
