//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PlanMealCount
    {
        public int TenentID { get; set; }
        public int planid { get; set; }
        public string planname1 { get; set; }
        public int MealType { get; set; }
        public string REFNAME1 { get; set; }
        public string Allowed { get; set; }
        public string FixFlex { get; set; }
        public string SWITCH1 { get; set; }
        public string SWITCH3 { get; set; }
        public Nullable<int> SWITCH4 { get; set; }
        public int REFID { get; set; }
    }
}
