//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ICTR_DT_Unique
    {
        public int TenentID { get; set; }
        public long MYTRANSID { get; set; }
        public int locationID { get; set; }
        public Nullable<long> MyProdID { get; set; }
        public string ProdName1 { get; set; }
        public string REFTYPE { get; set; }
        public string REFSUBTYPE { get; set; }
        public string UOM { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> OVERHEADAMOUNT { get; set; }
        public string BATCHNO { get; set; }
        public Nullable<int> BIN_ID { get; set; }
        public string BIN_TYPE { get; set; }
        public string GRNREF { get; set; }
        public Nullable<decimal> DISAMT { get; set; }
        public Nullable<decimal> DISPER { get; set; }
        public Nullable<decimal> TAXPER { get; set; }
        public Nullable<decimal> TAXAMT { get; set; }
    }
}
