//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DayCloseQTY
    {
        public int TenentID { get; set; }
        public Nullable<int> ToTenantID { get; set; }
        public int locationID { get; set; }
        public string TranType { get; set; }
        public Nullable<int> transid { get; set; }
        public Nullable<int> transsubid { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public int MYID { get; set; }
        public Nullable<long> MyProdID { get; set; }
        public Nullable<int> DTUOM { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> OVERHEADAMOUNT { get; set; }
        public Nullable<decimal> QtyOut { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> QtyReceived { get; set; }
        public long MYTRANSID { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public int QUANTITY { get; set; }
        public string Status { get; set; }
        public string Stutas { get; set; }
    }
}
