//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Moduel_map
    {
        public int MODULE_ID { get; set; }
        public string Module_Name { get; set; }
        public int LOCATION_ID { get; set; }
        public int TenentID { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public int USER_ID { get; set; }
    }
}
