//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DriverCheckList
    {
        public int TenentID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public int DayNumber { get; set; }
        public string EMAIL { get; set; }
        public string BUSPHONE1 { get; set; }
        public string MOBPHONE { get; set; }
        public string FAX { get; set; }
        public string CustRemark { get; set; }
        public Nullable<int> StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string CITY { get; set; }
        public string CityEnglish { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string REMARKS { get; set; }
        public string Block { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string Lane { get; set; }
        public int MainPlan { get; set; }
        public int Meal { get; set; }
        public Nullable<int> DeliverTime { get; set; }
        public string Delivery { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> DeliveryMeal { get; set; }
    }
}
