//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_KitchenPlanMealProductData
    {
        public int TenentID { get; set; }
        public int planid { get; set; }
        public string Plan_Eng { get; set; }
        public string Plan_Arabic { get; set; }
        public string Plan_Display { get; set; }
        public int MealType { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public int DayNumer { get; set; }
        public int serial_no { get; set; }
        public long MYPRODID { get; set; }
        public string Product_Eng { get; set; }
        public string Product_Arabic { get; set; }
        public int UOM { get; set; }
        public string Plan_in_Gram { get; set; }
        public string unique_package { get; set; }
        public int Plan_price1 { get; set; }
        public Nullable<int> Allowed_meal { get; set; }
        public string Meal_Eng { get; set; }
        public string Meal_Arabic { get; set; }
        public string UOM_English { get; set; }
        public string UOM_Arabic { get; set; }
        public long ProdNo { get; set; }
        public string DayName { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> Option1 { get; set; }
        public string Option2 { get; set; }
        public Nullable<int> Option3 { get; set; }
        public Nullable<System.DateTime> Option4 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public int REFID { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> Protein { get; set; }
        public Nullable<decimal> Carbs { get; set; }
        public Nullable<decimal> Fat { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<decimal> Item_cost { get; set; }
        public string ShortRemark { get; set; }
        public Nullable<int> KitchenWeek { get; set; }
    }
}
