//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MealTypeSetup
    {
        public int planid { get; set; }
        public string planname1 { get; set; }
        public int MealType { get; set; }
        public string REFNAME1 { get; set; }
        public long MYPRODID { get; set; }
        public string BarCode { get; set; }
        public string ProdName1 { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
    }
}
