//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PlanMealSumbyWeightCombine
    {
        public string WTableName { get; set; }
        public Nullable<System.DateTime> WExpectedDelDate { get; set; }
        public string WProductName { get; set; }
        public Nullable<decimal> WWeight { get; set; }
        public Nullable<int> WQty { get; set; }
        public int WTenentID { get; set; }
    }
}
