//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DisplayPlanMealInvoiceHDDT
    {
        public int TenentID { get; set; }
        public int MYTRANSID { get; set; }
        public int CustomerID { get; set; }
        public int DeliveryID { get; set; }
        public string customername { get; set; }
        public int planid { get; set; }
        public Nullable<int> TransID { get; set; }
        public string Planname { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string WeekofDay { get; set; }
        public string NameOfDay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TotalSubDays { get; set; }
        public Nullable<int> DeliveredDays { get; set; }
        public Nullable<System.DateTime> NExtDeliveryDate { get; set; }
        public Nullable<int> NExtDeliveryNum { get; set; }
        public Nullable<decimal> Total_price { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string CStatus { get; set; }
        public long MYPRODID { get; set; }
        public string ProdName1 { get; set; }
        public string ProductArabic { get; set; }
        public int UOM { get; set; }
        public string UOMNAME1 { get; set; }
        public string UOMArabic { get; set; }
        public Nullable<int> OprationDay { get; set; }
        public int DayNumber { get; set; }
        public Nullable<int> TotalWeek { get; set; }
        public Nullable<int> NoOfWeek { get; set; }
        public Nullable<int> DisplayWeek { get; set; }
        public Nullable<int> TotalDeliveryDay { get; set; }
        public Nullable<int> ActualDeliveryDay { get; set; }
        public Nullable<int> ExpectedDeliveryDay { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public Nullable<int> DeliveryMeal { get; set; }
        public Nullable<System.DateTime> ExpectedDelDate { get; set; }
        public Nullable<System.DateTime> ActualDelDate { get; set; }
        public Nullable<int> ReturnReason { get; set; }
        public Nullable<System.DateTime> ReasonDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> chiefID { get; set; }
        public Nullable<bool> SubscriptionOnHold { get; set; }
        public Nullable<System.DateTime> HoldDate { get; set; }
        public Nullable<System.DateTime> UnHoldDate { get; set; }
        public string HoldREmark { get; set; }
        public Nullable<int> Holdbyuser { get; set; }
        public int MealType { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string TrackStatus { get; set; }
        public Nullable<bool> ActiveDT { get; set; }
        public int LocalID_HD { get; set; }
        public string OfflineStatus_HD { get; set; }
        public int LocalID_DT { get; set; }
        public string OfflineStatus_DT { get; set; }
    }
}
