//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Product_fetch
    {
        public string UserProdID { get; set; }
        public string BarCode { get; set; }
        public string AlternateCode1 { get; set; }
        public string AlternateCode2 { get; set; }
        public string ShortName { get; set; }
        public string ProdName1 { get; set; }
        public string ProdName2 { get; set; }
        public string ProdName3 { get; set; }
        public string DescToprint { get; set; }
        public string BrandName { get; set; }
        public string keywords { get; set; }
        public string REMARKS { get; set; }
        public int TenentID { get; set; }
        public long LOCATION_ID { get; set; }
        public long MYPRODID { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<bool> Serialized { get; set; }
        public Nullable<bool> MultiSize { get; set; }
        public Nullable<bool> MultiUOM { get; set; }
        public Nullable<bool> MultiColor { get; set; }
        public Nullable<bool> MultiBinStore { get; set; }
        public Nullable<bool> Perishable { get; set; }
        public Nullable<bool> SaleAllow { get; set; }
        public Nullable<bool> PurAllow { get; set; }
        public Nullable<decimal> msrp { get; set; }
        public string currency { get; set; }
        public string ACTIVE { get; set; }
        public string Warranty { get; set; }
        public string IsSoftware { get; set; }
        public Nullable<long> MainCategoryID { get; set; }
    }
}
