//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FunctionUserWiseDetailList
    {
        public long TenentID { get; set; }
        public int MENUID { get; set; }
        public Nullable<int> MASTER_ID { get; set; }
        public string MENU_TYPE { get; set; }
        public string MENU_NAME1 { get; set; }
        public string LINK { get; set; }
        public string Urloption { get; set; }
        public string URLREWRITE { get; set; }
        public string MENU_LOCATION { get; set; }
        public Nullable<decimal> MENU_ORDER { get; set; }
        public Nullable<int> ADDFLAGE { get; set; }
        public Nullable<int> EDITFLAGE { get; set; }
        public Nullable<int> DELFLAGE { get; set; }
        public Nullable<int> PRINTFLAGE { get; set; }
        public Nullable<int> AMIGLOBALE { get; set; }
        public string SMALLTEXT { get; set; }
        public Nullable<int> MYPERSONAL { get; set; }
        public Nullable<System.DateTime> ACTIVETILLDATE { get; set; }
        public string ICONPATH { get; set; }
        public string ActualURL { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string LOGIN_ID { get; set; }
        public string PASSWORD { get; set; }
    }
}
