//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTransactionSerialize
    {
        public int TenentID { get; set; }
        public long MYPRODID { get; set; }
        public string Serial_Number { get; set; }
        public long MYTRANSID { get; set; }
        public int locationID { get; set; }
        public Nullable<int> UOM { get; set; }
        public string UserProdID { get; set; }
        public string BarCode { get; set; }
        public string AlternateCode1 { get; set; }
        public string AlternateCode2 { get; set; }
        public string ProdName1 { get; set; }
        public string ShortName { get; set; }
        public string ProdName2 { get; set; }
        public string ProdName3 { get; set; }
        public string DescToprint { get; set; }
        public string ExtraField1 { get; set; }
        public string Status { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string REMARKS { get; set; }
        public string keywords { get; set; }
        public Nullable<decimal> CUSTVENDID { get; set; }
        public string NOTES { get; set; }
        public string REFERENCE { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> TOTAMT { get; set; }
    }
}
