//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CompanyMaster
    {
        public int TenentID { get; set; }
        public int COMPID { get; set; }
        public string COMPNAME1 { get; set; }
        public string COMPNAME2 { get; set; }
        public string COMPNAME3 { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string Keyword { get; set; }
        public string REMARKS { get; set; }
        public string BUSPHONE1 { get; set; }
        public string MOBPHONE { get; set; }
        public string CityEnglish { get; set; }
        public string MYNAME1 { get; set; }
        public string EMAIL1 { get; set; }
        public string Active { get; set; }
    }
}
