//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CheckLogin_Win
    {
        public int TenentID { get; set; }
        public string Shopid { get; set; }
        public int TenentGroupID { get; set; }
        public Nullable<int> PhysicalLocID { get; set; }
        public string COMPNAME1 { get; set; }
        public string COMPNAME2 { get; set; }
        public string COMPNAME3 { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<int> ARABIC { get; set; }
        public string Mac_Addr { get; set; }
        public string DefaultLanguage { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public Nullable<System.DateTime> installDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string AppVer { get; set; }
        public Nullable<System.DateTime> AppVerDate { get; set; }
        public string DBVer { get; set; }
        public Nullable<System.DateTime> DBVerDate { get; set; }
        public long id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
    }
}
