//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustCreditReport
    {
        public long TrxID { get; set; }
        public string Date { get; set; }
        public Nullable<long> CustID { get; set; }
        public string Name { get; set; }
        public string OrderID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Description { get; set; }
    }
}
