//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_planmealcustinvoice_HD
    {
        public int tenentid { get; set; }
        public int customerid { get; set; }
        public int planid { get; set; }
        public int mealtype { get; set; }
        public int deliveryid { get; set; }
        public Nullable<System.DateTime> ExpectedDelDate { get; set; }
        public int mytransid { get; set; }
        public Nullable<int> driverid { get; set; }
        public string carbsproteinrmk { get; set; }
        public long myprodid { get; set; }
        public int DayNumber { get; set; }
        public string NameOfDay { get; set; }
        public Nullable<int> deliverytime { get; set; }
        public Nullable<System.DateTime> NExtDeliveryDate { get; set; }
        public string MobPhone { get; set; }
    }
}
