//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRintInvoice
    {
        public long salesid { get; set; }
        public string paytype { get; set; }
        public Nullable<decimal> Payamount { get; set; }
        public Nullable<decimal> charAmt { get; set; }
        public Nullable<decimal> due { get; set; }
        public Nullable<decimal> dis { get; set; }
        public Nullable<decimal> Delivery_Cahrge { get; set; }
        public Nullable<decimal> vat { get; set; }
        public string s_time { get; set; }
        public string custID { get; set; }
        public string empID { get; set; }
        public string Note { get; set; }
        public string TrxType { get; set; }
        public int sales_id { get; set; }
        public long item_id { get; set; }
        public string itemName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> RetailsPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> profit { get; set; }
        public string sales_time { get; set; }
        public string product_name_print { get; set; }
        public string Shopid { get; set; }
        public int TenentID { get; set; }
        public int ID { get; set; }
        public string Terminal_Type { get; set; }
        public string CompanyName { get; set; }
        public string Branchname { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<decimal> VAT1 { get; set; }
        public Nullable<decimal> Dis1 { get; set; }
        public string VATRegiNo { get; set; }
        public string Expr3 { get; set; }
        public string Footermsg { get; set; }
        public string InvAddtionalLine { get; set; }
        public int C_TID { get; set; }
        public long C_ID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Phone1 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string NameArabic { get; set; }
        public string TaxApply { get; set; }
        public string PeopleType { get; set; }
        public string UOM { get; set; }
        public string ExpiryDate { get; set; }
        public string BatchNo { get; set; }
        public string CustItemCode { get; set; }
        public string BarCode { get; set; }
        public string Logo { get; set; }
        public string Customer { get; set; }
    }
}
