//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Return_Item
    {
        public long salerid { get; set; }
        public string paytype { get; set; }
        public Nullable<decimal> Payamount { get; set; }
        public Nullable<decimal> charAmt { get; set; }
        public Nullable<decimal> due { get; set; }
        public Nullable<decimal> dis { get; set; }
        public Nullable<decimal> vat { get; set; }
        public string s_time { get; set; }
        public string custID { get; set; }
        public string empID { get; set; }
        public string Note { get; set; }
        public string TrxType { get; set; }
        public long return_id { get; set; }
        public string item_id { get; set; }
        public string itemName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> RetailsPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Shopid { get; set; }
        public int TenentID { get; set; }
        public int ID { get; set; }
        public string Terminal_Type { get; set; }
        public string CompanyName { get; set; }
        public string Branchname { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<decimal> Expr2 { get; set; }
        public string VATRegiNo { get; set; }
        public string Expr3 { get; set; }
        public string Footermsg { get; set; }
        public string InvAddtionalLine { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Insta { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string DbPath { get; set; }
        public string ImgPath { get; set; }
        public int Expr4 { get; set; }
        public long Expr5 { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Expr6 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PeopleType { get; set; }
        public Nullable<System.DateTime> Expr7 { get; set; }
        public string Expr8 { get; set; }
        public Nullable<System.DateTime> Expr9 { get; set; }
        public string Expr10 { get; set; }
        public Nullable<int> Expr11 { get; set; }
        public string UOM { get; set; }
        public string ExpiryDate { get; set; }
        public string BatchNo { get; set; }
    }
}
