//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_solditemscost
    {
        public Nullable<long> MyProdID { get; set; }
        public string ProdName1 { get; set; }
        public Nullable<decimal> basecost { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
    }
}
