//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWProductPring
    {
        public long MYPRODID { get; set; }
        public string UserProdID { get; set; }
        public string BarCode { get; set; }
        public string AlternateCode1 { get; set; }
        public string AlternateCode2 { get; set; }
        public string UOM { get; set; }
        public string Brand { get; set; }
        public string ShortName { get; set; }
        public string ProdName1 { get; set; }
        public string ProdName2 { get; set; }
        public string ProdName3 { get; set; }
        public string DescToprint { get; set; }
        public Nullable<decimal> msrp { get; set; }
    }
}
