//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public int WebPageID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public string PageIcon { get; set; }
        public Nullable<int> PageOrder { get; set; }
        public string PageTitle { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Description { get; set; }
        public string ArabicPageTitle { get; set; }
    }
}
