//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_tblinvoice_PrintFile
    {
        public int ID { get; set; }
        public string FileDisplayName { get; set; }
        public string FileName { get; set; }
        public string File_Type { get; set; }
    }
}
