//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_tbl_terminalLocation
    {
        public int TenentID { get; set; }
        public int ID { get; set; }
        public string Terminal_Type { get; set; }
        public string CompanyName { get; set; }
        public string Branchname { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Dis { get; set; }
        public string VATRegiNo { get; set; }
        public string Shopid { get; set; }
        public string Footermsg { get; set; }
        public string InvAddtionalLine { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Insta { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string DbPath { get; set; }
        public string ImgPath { get; set; }
        public Nullable<int> syncAfter { get; set; }
        public Nullable<int> dayofSync { get; set; }
        public Nullable<int> Salesync { get; set; }
    }
}
