//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_WebRegistration
    {
        public int ID { get; set; }
        public int TenentID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string CompName1 { get; set; }
        public string CompName2 { get; set; }
        public string CompName3 { get; set; }
        public string DefaultLANGUAGE { get; set; }
        public string CompAddress { get; set; }
        public string CompPhone { get; set; }
        public string CompWebside { get; set; }
        public string UserLastname { get; set; }
        public string UserAddress { get; set; }
        public string UserPhone { get; set; }
        public string UserBirthdate { get; set; }
        public string UserEmail { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> RegStatus { get; set; }
    }
}
