//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_tbl_orderWay_Maintenance
    {
        public int TenentID { get; set; }
        public int ID { get; set; }
        public string OrderWayID { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<decimal> Commission_per { get; set; }
        public Nullable<decimal> Commission_Amount { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> Paid_Commission { get; set; }
        public Nullable<decimal> Pending_Commission { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
