//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_usermgt
    {
        public int TenentID { get; set; }
        public long id { get; set; }
        public string Name { get; set; }
        public string Father_name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public string position { get; set; }
        public string imagename { get; set; }
        public string Shopid { get; set; }
        public Nullable<System.DateTime> logdate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
