//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_TblProductRelated
    {
        public int TenentID { get; set; }
        public int LOCATION_ID { get; set; }
        public long MYPRODID { get; set; }
        public long RalatedProdID { get; set; }
        public Nullable<int> sortNO { get; set; }
        public Nullable<bool> AlwaysShow { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> CRUP_ID { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
    }
}
