//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_sales_item
    {
        public int TenentID { get; set; }
        public int sales_id { get; set; }
        public long item_id { get; set; }
        public string itemName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> RetailsPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> profit { get; set; }
        public string sales_time { get; set; }
        public string itemcode { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string taxapply { get; set; }
        public Nullable<int> status { get; set; }
        public string UOM { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> OnlineTransID { get; set; }
        public Nullable<int> SynID { get; set; }
        public string InvoiceNO { get; set; }
        public Nullable<decimal> returnQty { get; set; }
        public Nullable<decimal> returnTotal { get; set; }
        public string product_name_print { get; set; }
        public string ExpiryDate { get; set; }
        public string OrderStutas { get; set; }
        public string SoldBy { get; set; }
        public Nullable<int> COD { get; set; }
        public string Driver { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string PaymentMode { get; set; }
        public string Shopid { get; set; }
        public string c_id { get; set; }
        public string BatchNo { get; set; }
        public string OrderWay { get; set; }
        public string CustItemCode { get; set; }
        public string BarCode { get; set; }
        public Nullable<int> Live_MytranceIDHD { get; set; }
        public Nullable<int> Live_MyidDT { get; set; }
        public Nullable<System.DateTime> Live_date { get; set; }
        public Nullable<int> ISPaymentCredit { get; set; }
        public string Remarks { get; set; }
    }
}
