//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Win_tbl_item_uom_price
    {
        public int TenentID { get; set; }
        public int ID { get; set; }
        public int itemID { get; set; }
        public string UOMID { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> msrp { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> ORIGINALPRICE { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Uploadby { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string Syncby { get; set; }
        public Nullable<int> SynID { get; set; }
        public string Deleted { get; set; }
        public Nullable<int> OpQty { get; set; }
        public Nullable<int> OnHand { get; set; }
        public Nullable<int> QtyOut { get; set; }
        public Nullable<int> QtyConsumed { get; set; }
        public Nullable<int> QtyReserved { get; set; }
        public Nullable<int> QtyRecived { get; set; }
        public Nullable<int> minQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> total_cost_price { get; set; }
        public Nullable<decimal> total_retail_price { get; set; }
        public string ExpiryDate { get; set; }
        public string RecipeType { get; set; }
        public Nullable<int> recNo { get; set; }
    }
}
